### ISSUE TITLE
NullPointerException in AttributeOps

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1025]
I've seen this pop up at least a few times (50+) in the logs while compiling the community build
```scala
[warn] java.lang.NullPointerException
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$$anonfun$12.apply(AttributesOps.scala:228)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$$anonfun$12.apply(AttributesOps.scala:228)
[warn]  at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:113)
[warn]  at scala.collection.immutable.List.find(List.scala:84)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.tryFindMtree(AttributesOps.scala:228)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:388)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:150)
[warn]  at scala.reflect.internal.Trees$$anonfun$traverseMemberDef$1$1.apply$mcV$sp(Trees.scala:1207)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.internal.Trees$class.traverseMemberDef$1(Trees.scala:1203)
[warn]  at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1328)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:390)
[warn]  at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:150)
[warn]  at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
[warn]  at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1326)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
```

**Comment by olafurpg** [comment]
The culprit line is here https://github.com/scalameta/scalameta/blob/a6014efd1e0ed5281df8a972535766755f5ea299/scalahost/nsc/src/main/scala/scala/meta/internal/semantic/AttributesOps.scala#L228

**Comment by xeno-by** [comment]
Looks like we need to insert a null check to guard the invocation of `isPrimaryConstructor`.
