### ISSUE TITLE
Classpath.apply crashes with java.lang.SecurityException

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1120]
```
scala> import scala.meta.io._
import scala.meta.io._

scala> Classpath("foo:bar")
java.lang.SecurityException: Prohibited package name: java.io
  at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at org.langmeta.io.Classpath$.apply(Multipath.scala:79)
  ... 31 elided
```

**Comment by xeno-by** [comment]
The crash only happens when I use `bin/scala` from the standard distribution. Running this code from `sbt console` works just fine.

**Comment by xeno-by** [comment]
Moreover, the crash only happens on Scala 2.12, not on Scala 2.11.
