### ISSUE TITLE
Loading semanticsdb attempts to visit paths that are not accessible

### ISSUE THREAD

**Issue by fikovnik** [scalameta/scalameta#1168]
Here is the corresponding exception when running scala-meta 2.1.2:

```
java.nio.file.AccessDeniedException: /home/guest/test/./private
java.io.UncheckedIOException: java.nio.file.AccessDeniedException:  /home/guest/test/./private
    at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
    at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
    at java.util.Iterator.forEachRemaining(Iterator.java:115)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.langmeta.internal.io.PlatformFileIO$.listAllFilesRecursively(PlatformFileIO.scala:40)
    at org.langmeta.internal.io.FileIO$.listAllFilesRecursively(FileIO.scala:28)
    at org.langmeta.io.Multipath.$anonfun$deep$1(Multipath.scala:43)
    at org.langmeta.io.Multipath.$anonfun$deep$1$adapted(Multipath.scala:16)
    at scala.collection.immutable.List.foreach(List.scala:389)
    at org.langmeta.io.Multipath.deep(Multipath.scala:16)
    at org.langmeta.io.Multipath.deep$(Multipath.scala:14)
    at org.langmeta.io.Classpath.deep(Multipath.scala:68)
    at org.langmeta.internal.semanticdb.vfs.Database$.load(Database.scala:13)
    at scala.meta.internal.SemanticdbPipeline$SemanticdbJvmComponent$PersistSemanticdbPhase.run(SemanticdbPipeline.scala:104)
```

The problem is that the `PlatformFileIO.listAllFilesRecursively` is using `files.walk`. This method _visits all levels of the file tree_, regardless of the permissions.

**Comment by olafurpg** [comment]
Thank you for reporting! What should we use instead of Files.walk?
