### ISSUE TITLE
java.lang.UnsupportedOperationException: Position.point on NoPosition

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1173]
while running semanticdb-scalac on the slick codebase
```
[warn] failed to generate semanticdb for /Users/ollie/dev/slick/slick/src/main/scala/slick/ast/Node.scala:
[warn] java.lang.UnsupportedOperationException: Position.point on NoPosition
[warn] 	at scala.reflect.internal.util.Position.fail(Position.scala:17)
[warn] 	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:95)
[warn] 	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:90)
[warn] 	at scala.meta.internal.semanticdb.InputOps$XtensionGPositionMPosition.toMeta(InputOps.scala:50)
[warn] 	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:27)
```

**Comment by olafurpg** [comment]
Hit on this again

```
[warn] 	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:95)
[warn] 	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:90)
[warn] 	at scala.meta.internal.semanticdb.InputOps$XtensionGPositionMPosition.toMeta(InputOps.scala:50)
```
