### ISSUE TITLE
Parser crash on spark codebase

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1177]
https://github.com/apache/spark/blob/96e947ed6c945bdbe71c308112308489668f19ac/sql/core/src/main/scala/org/apache/spark/sql/execution/ColumnarBatchScan.scala

```
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@13815042
        at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:231)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:276)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:31)
        at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:287)
        at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:21)
        at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:10)
        at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:183)
        at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:183)
        at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:140)
        at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3465)
        at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
        at scalafix.cli.CliRunner.unsafeHandleInput(CliRunner.scala:117)
        at scalafix.cli.CliRunner.safeHandleInput(CliRunner.scala:185)
        at scalafix.cli.CliRunner.$anonfun$run$1(CliRunner.scala:76)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
```

**Comment by tobyweston** [comment]
I see this for several of my source files (not spark), there's no clue what in the file is breaking the invariant.

```
[error] org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
[error] found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
[error] where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@37361989
[error]	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
[error]	at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222)
[error]	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:231)
[error]	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:276)
```

**Comment by MasseGuillaume** [comment]
@tobyweston can you provide us with the file or if possible a minimal input that produces the same error?

**Comment by ShaneDelmore** [comment]
Do you have files with windows line endings in the codebase?  I have seen this when someone accidentally checked in a file with \n\r instead of \n
