### ISSUE TITLE
MatchError in semanticdb

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1194]
Encountered while playing around with it in language-server
```
tring#
23:39:12.907 ERROR s.m.l.Semanticdbs$ - Failed to emit semanticdb for /Users/ollie/dev/language-server/test-workspace/src/main/scala/example/User.scala
scala.MatchError: <notype> (of class scala.reflect.internal.Types$NoType$)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.encode$1(SymbolOps.scala:54)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.jvmSignature$1(SymbolOps.scala:70)
```

**Comment by olafurpg** [comment]
Encountered another error in SymbolOps when calling erasure
```
00:05:32.816 ERROR s.m.l.Semanticdbs$ - Failed to emit semanticdb for /Users/ollie/dev/language-server/test-workspace/src/test/scala/example/UserTest.scala
java.lang.NullPointerException: null
	at scala.reflect.internal.Types.refinedType(Types.scala:3573)
	at scala.reflect.internal.Types.refinedType$(Types.scala:3572)
	at scala.reflect.internal.SymbolTable.refinedType(SymbolTable.scala:16)
	at scala.reflect.internal.Types.intersectionType(Types.scala:3657)
	at scala.reflect.internal.Types.intersectionType$(Types.scala:3655)
	at scala.reflect.internal.SymbolTable.intersectionType(SymbolTable.scala:16)
	at scala.reflect.internal.Types.singletonBounds(Types.scala:3925)
	at scala.reflect.internal.Types.singletonBounds$(Types.scala:3925)
	at scala.reflect.internal.SymbolTable.singletonBounds(SymbolTable.scala:16)
	at scala.reflect.internal.Symbols$TermSymbol.existentialBound(Symbols.scala:2836)
	at scala.reflect.internal.Symbols$TermSymbol.existentialBound(Symbols.scala:2759)
	at scala.reflect.internal.ExistentialsAndSkolems.$anonfun$existentialBoundsExcludingHidden$2(ExistentialsAndSkolems.scala:64)
	at scala.reflect.internal.util.Collections.$anonfun$mapFrom$1(Collections.scala:195)
	at scala.reflect.internal.ExistentialsAndSkolems.existentialBoundsExcludingHidden(ExistentialsAndSkolems.scala:64)
	at scala.reflect.internal.ExistentialsAndSkolems.packSymbols(ExistentialsAndSkolems.scala:87)
	at scala.reflect.internal.ExistentialsAndSkolems.packSymbols$(ExistentialsAndSkolems.scala:115)
	at scala.reflect.internal.SymbolTable.packSymbols(SymbolTable.scala:16)
	at scala.reflect.internal.transform.UnCurry$$anon$1$$anon$2.apply(UnCurry.scala:39)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.applyToSymbolInfo(TypeMaps.scala:215)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.loop$1(TypeMaps.scala:224)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.noChangeToSymbols(TypeMaps.scala:226)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:240)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:41)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:131)
	at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:53)
	at scala.reflect.internal.transform.Transforms.transformedType(Transforms.scala:40)
	at scala.reflect.internal.transform.Transforms.transformedType$(Transforms.scala:39)
	at scala.reflect.internal.SymbolTable.transformedType(SymbolTable.scala:16)
	at scala.reflect.internal.Types$TypeApiImpl.erasure(Types.scala:228)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.jvmSignature$1(SymbolOps.scala:68)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:74)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:34)
```

The presentation compiler is permissive for broken code and semanticdb-scalac should be so too

**Comment by olafurpg** [comment]
Another interesting error I'm hitting on regularly 
```
19:39:54.564 ERROR s.m.l.Semanticdbs$ - Failed to emit semanticdb for /Users/ollie/dev/language-server/metaserver/src/main/scala/scala/meta/languageserver/compiler/ScalacProvider.scala
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving constructor ServerConfig
	at scala.reflect.internal.Symbols$Symbol.$anonfun$info$3(Symbols.scala:1518)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:570)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1516)
	at scala.meta.internal.semanticdb.SymbolOps$XtensionGSymbolMSymbol.jvmSignature$1(SymbolOps.scala:68)
```
Looking forward to the new pending release!
