### ISSUE TITLE
Crashes in toDenotation under presentation compiler

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1197]
Now that toSymbol succeeds `toDenotation` started failing
```
20:40:59.902 ERROR s.m.l.c.Scalac - Failed to emit semanticdb for file:///Users/ollie/dev/language-server/test-workspace/src/main/scala/example/User.scala
java.lang.ClassCastException: scala.reflect.internal.Types$ClassInfoType cannot be cast to scala.reflect.internal.Symbols$Symbol
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:642)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readType$2(UnPickler.scala:368)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbols$1(UnPickler.scala:365)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:408)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.$anonfun$completeInternal$1(UnPickler.scala:714)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.completeInternal(UnPickler.scala:714)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:741)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.meta.internal.semanticdb.DenotationOps$XtensionGSymbolMDenotation.info(DenotationOps.scala:94)
	at scala.meta.internal.semanticdb.DenotationOps$XtensionGSymbolMDenotation.toDenotation(DenotationOps.scala:109)
	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.saveDenotation$1(DocumentOps.scala:180)
```

**Comment by olafurpg** [comment]
New one in our CI https://travis-ci.org/scalameta/language-server/jobs/316888572#L743
```
11:55:57.093 ERROR s.m.l.Semanticdbs$ - Failed to emit semanticdb for deprecation.scala

scala.reflect.internal.Types$TypeError: illegal cyclic inheritance involving class AbstractSeq

	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1528)

	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1471)

	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)

	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1379)

	at scala.reflect.internal.Types$PolyType.baseTypeSeq(Types.scala:2615)

	at scala.reflect.internal.Types$TypeRef.baseTypeSeqImpl(Types.scala:2310)

	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef(Types.scala:2476)

	at scala.reflect.internal.Types.defineBaseTypeSeqOfTypeRef$(Types.scala:2467)

	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfTypeRef(SymbolTable.scala:16)

	at scala.reflect.internal.Types$TypeRef.baseTypeSeq(Types.scala:2323)

	at scala.reflect.internal.Types$Type.baseTypeIndex(Types.scala:920)

	at scala.reflect.internal.Types.isNew$1(Types.scala:1451)

	at scala.reflect.internal.Types.addMixinBaseClasses$1(Types.scala:1460)

	at scala.reflect.internal.Types.computeBaseClasses(Types.scala:1462)

	at scala.reflect.internal.Types.computeBaseClasses$(Types.scala:1439)

	at scala.reflect.internal.SymbolTable.computeBaseClasses(SymbolTable.scala:16)

	at scala.reflect.internal.Types.$anonfun$defineBaseClassesOfCompoundType$2(Types.scala:1583)

	at scala.reflect.internal.Types$CompoundType.memo(Types.scala:1410)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType(Types.scala:1583)

	at scala.reflect.internal.Types.define$1(Types.scala:1550)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType(Types.scala:1551)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType$(Types.scala:1549)

	at scala.reflect.internal.SymbolTable.defineBaseClassesOfCompoundType(SymbolTable.scala:16)

	at scala.reflect.internal.Types$CompoundType.baseClasses(Types.scala:1393)

	at scala.reflect.internal.Types$PolyType.baseClasses(Types.scala:2617)

	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2304)

	at scala.reflect.internal.Types.computeBaseClasses(Types.scala:1448)

	at scala.reflect.internal.Types.computeBaseClasses$(Types.scala:1439)

	at scala.reflect.internal.SymbolTable.computeBaseClasses(SymbolTable.scala:16)

	at scala.reflect.internal.Types.$anonfun$defineBaseClassesOfCompoundType$2(Types.scala:1583)

	at scala.reflect.internal.Types$CompoundType.memo(Types.scala:1410)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType(Types.scala:1583)

	at scala.reflect.internal.Types.define$1(Types.scala:1550)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType(Types.scala:1551)

	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType$(Types.scala:1549)

	at scala.reflect.internal.SymbolTable.defineBaseClassesOfCompoundType(SymbolTable.scala:16)

	at scala.reflect.internal.Types$CompoundType.baseClasses(Types.scala:1393)

	at scala.reflect.internal.Types$PolyType.baseClasses(Types.scala:2617)

	at scala.reflect.internal.Types$Type.findDecl(Types.scala:1002)

	at scala.reflect.internal.Types$Type.decl(Types.scala:586)

	at scala.reflect.internal.Symbols$ClassSymbol.primaryConstructor(Symbols.scala:3298)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.saveDenotation$1(DocumentOps.scala:178)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.success$1(DocumentOps.scala:185)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryMpos$1(DocumentOps.scala:216)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryFindMtree(DocumentOps.scala:262)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:441)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:149)

	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1324)

	at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)

	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)

	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)

	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)

	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)

	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:443)

	at 
```
