### ISSUE TITLE
Metacp crashes on Java enums

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1283]
Rebasing #1278 on top of #1271 I hit on an error running scalap on LinkOption.NOFOLLOW_LINKS

```
scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected failure
	at scala.tools.scalap.scalax.rules.Rules.$anonfun$expect$1(Rules.scala:75)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigSymbol.applyRule(Symbol.scala:24)
	at scala.tools.scalap.scalax.rules.scalasig.SymbolInfoSymbol.infoType$lzycompute(Symbol.scala:59)
	at scala.tools.scalap.scalax.rules.scalasig.SymbolInfoSymbol.infoType(Symbol.scala:59)
	at scala.meta.cli.metacp.Main$.stpe(Main.scala:337)
	at scala.meta.cli.metacp.Main$.sinfo(Main.scala:81)
```

**Comment by olafurpg** [comment]
Fixed in #1278
