### ISSUE TITLE
Metacp does not support constant ExistentialType

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1306]
While running metacp on akka I hit on the following error
```
error: can't convert jar:file:///Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.9/akka-actor_2.12-2.5.9.jar!/akka/dispatch/Mailboxes.class
java.lang.RuntimeException: unsupported const ExistentialType(TypeRefType(ThisType(akka.dispatch),akka.dispatch.RequiresMessageQueue,List(TypeRefType(NoPrefixType,TypeSymbol(_$4, owner=169, flags=100, info=135 ),List()))),List(TypeSymbol(_$4, owner=169, flags=100, info=135 )))
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.metacp.Main$.loop$2(Main.scala:269)
	at scala.meta.internal.metacp.Main$.loop$2(Main.scala:298)
	at scala.meta.internal.metacp.Main$.stpe(Main.scala:346)
	at scala.meta.internal.metacp.Main$.sinfo(Main.scala:83)
	at scala.meta.internal.metacp.Main$.$anonfun$process$4(Main.scala:41)
```

I expected metacp to handle ExistentialType constants. 

I suspect the original signature is from here https://github.com/akka/akka/blob/b3a27d1c9f7504a982327d7e885a36a5a2c8f7a2/akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala#L77

**Comment by xeno-by** [comment]
Scalac has a special kind of constant types that carry `Class[_]`. This is total craziness, and we shouldn't model this as a literal type. I suggest that we widen such types to `Class[<whatever type argument is there>]`.
