### ISSUE TITLE
RuntimeException: unsupported const Constant(value MINUTES): Constant(TermName("MINUTES"))

### ISSUE THREAD

**Issue by tobyweston** [scalameta/scalameta#1354]
Not sure if this is the same issue as #1274 or not but I get the following error,

```
error] failed to generate semanticdb for C:\Users\westtob\code\github\temperature-machine\src\main\scala\bad\robot\temperature\client\BlazeHttpClient.scala:
[error] java.lang.RuntimeException: unsupported const Constant(value SECONDS): Constant(TermName("SECONDS"))
[error]	at scala.sys.package$.error(package.scala:27)
[error]	at scala.meta.internal.semanticdb.scalac.TypeOps$XtensionGTypeSType.loop$1(TypeOps.scala:62)
[error]	at scala.meta.internal.semanticdb.scalac.TypeOps$XtensionGTypeSType.loop$1(TypeOps.scala:87)
[error]	at scala.meta.internal.semanticdb.scalac.TypeOps$XtensionGTypeSType.toSemantic(TypeOps.scala:137)
[error]	at scala.meta.internal.semanticdb.scalac.DenotationOps$XtensionGSymbolMDenotation.newInfo(DenotationOps.scala:109)
[error]	at scala.meta.internal.semanticdb.scalac.DenotationOps$XtensionGSymbolMDenotation.toDenotation(DenotationOps.scala:139)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.add$1(DocumentOps.scala:198)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.saveDenotation$1(DocumentOps.scala:215)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.success$1(DocumentOps.scala:225)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryMpos$1(DocumentOps.scala:256)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryFindMtree(DocumentOps.scala:302)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:481)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:449)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[error]	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2484)
[error]	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
[error]	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1296)
[error]	at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[error]	at s
```

against

```
import scala.concurrent.duration._

  private val DefaultExecutor = {
    ExecutionContext.fromExecutor(
      new ThreadPoolExecutor(1, getRuntime.availableProcessors() * 6, 60L, SECONDS, new LinkedBlockingQueue[Runnable](), TemperatureMachineThreadFactory("client"))
    )
  }
```
Full source [here](https://github.com/tobyweston/temperature-machine/blob/5b689780fe5b382833ab55e442b420751738b5c9/src/main/scala/bad/robot/temperature/client/BlazeHttpClient.scala)

and similarly, 

```
[error]failed to generate semanticdb for C:\Users\westtob\code\github\temperature-machine\src\main\scala\bad\robot\temperature\server\ConnectionsEndpoint.scala:
[error]java.lang.RuntimeException: unsupported const Constant(value MINUTES): Constant(TermName("MINUTES"))
[error]	at scala.sys.package$.error(package.scala:27)
[error]	at scala.meta.internal.semanticdb.scalac.TypeOps$XtensionGTypeSType.loop$1(TypeOps.scala:62)
[error]	at scala.meta.internal.semanticdb.scalac.TypeOps$XtensionGTypeSType.toSemantic(TypeOps.scala:137)
[error]	at scala.meta.internal.semanticdb.scalac.DenotationOps$XtensionGSymbolMDenotation.newInfo(DenotationOps.scala:109)
[error]	at scala.meta.internal.semanticdb.scalac.DenotationOps$XtensionGSymbolMDenotation.toDenotation(DenotationOps.scala:139)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.add$1(DocumentOps.scala:198)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.saveDenotation$1(DocumentOps.scala:215)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.success$1(DocumentOps.scala:225)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.$anonfun$tryFindMtree$16(DocumentOps.scala:358)
[error]	at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.$anonfun$tryFindMtree$16$adapted(DocumentOps.scala:349)
[error]	at scala.collection.immutable.List.foreach(List.scala:389)
```

against

```
import java.time.temporal.ChronoUnit.{MINUTES => minutes}
```

**Comment by olafurpg** [comment]
What version are you using? I think this bug has been fixed recently, but I'm curious to know why you're hitting on that path in the first place since I'm not aware of any application using the new Type in semanticdb

**Comment by tobyweston** [comment]
I'm going via scalafix 1.6.0-M2 which I *think* is using scalameta 3.3.1...

**Comment by olafurpg** [comment]
I don't recommend using scalafix 0.6 milestone releases for now, we are still at least a couple weeks from having something ready for stable use. I recommend you stay on 0.5.10 for now.
 
I think this bug has been fixed but I'll add your minimized input to our test suite just to be sure :)

Thanks for reporting btw!

**Comment by olafurpg** [comment]
I'm unable to reproduce on master. I think this has been fixed for a long time, we have a test case for java enums https://github.com/scalameta/scalameta/blob/f7b2d17eb03298ee5049fb5b1bd69a059b608065/semanticdb/integration/src/main/scala/example/Types.scala#L107
