### ISSUE TITLE
Javacp crashes on classes from the empty package

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1371]
```
$ cat ClassSuffix.java
public class ClassSuffix {
}
$ javac *.java
$ metacp .
error: can't convert /Users/eburmako/Projects/scalameta/sandbox/./ClassSuffix.class
java.lang.IllegalArgumentException: Missing $ or / from symbol 'ClassSuffix'
	at scala.meta.internal.javacp.Javacp$.sname(Javacp.scala:369)
	at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:60)
	at scala.meta.internal.javacp.Javacp$.parse(Javacp.scala:21)
	at scala.meta.internal.metacp.Main$$anon$1.visitFile(Main.scala:34)
	at scala.meta.internal.metacp.Main$$anon$1.visitFile(Main.scala:19)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.langmeta.io.Multipath.$anonfun$visit$1(Multipath.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.langmeta.io.Multipath.visit(Multipath.scala:72)
	at org.langmeta.io.Multipath.visit$(Multipath.scala:71)
	at org.langmeta.io.Classpath.visit(Multipath.scala:92)
	at scala.meta.internal.metacp.Main.process(Main.scala:18)
	at scala.meta.cli.Metacp$.process(Metacp.scala:20)
	at scala.meta.cli.Metacp$.main(Metacp.scala:8)
	at scala.meta.cli.Metacp.main(Metacp.scala)
```

**Comment by xeno-by** [comment]
Fixed in Fixed in https://github.com/scalameta/scalameta/pull/1430.
