### ISSUE TITLE
MatchError in ScalametaTokenizer

### ISSUE THREAD

**Issue by DavidGregory084** [scalameta/scalameta#1382]
This occurred while running sbt-scalafix 0.5.10 on a Scala 2.12.4 project, I think this means semanticdb-scalac 2.1.7

Full stacktrace from SBT is as follows
```
[warn] failed to generate semanticdb for /home/david/Repos/application-services/framework/service/src/main/scala/service/delphicomms/IcfRecord.scala:
[warn] scala.MatchError: 8 (of class java.lang.Integer)
[warn] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:234)
[warn] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:276)
[warn] 	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:31)
[warn] 	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:287)
[warn] 	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:21)
[warn] 	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:10)
[warn] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:183)
[warn] 	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:183)
[warn] 	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:140)
[warn] 	at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3465)
[warn] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[warn] 	at scala.meta.internal.semanticdb.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:12)
[warn] 	at scala.meta.internal.semanticdb.DocumentOps$XtensionCompilationUnitDocument.toDocument(DocumentOps.scala:145)
[warn] 	at scala.meta.internal.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:59)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
[warn] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[warn] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[warn] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
[warn] 	at scala.meta.internal.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:67)
[warn] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[warn] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[warn] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[warn] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[warn] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
[warn] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
[warn] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
[warn] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[warn] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[warn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[warn] 	at java.lang.reflect.Method.invoke(Method.java:498)
[warn] 	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
[warn] 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
[warn] 	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
[warn] 	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
[warn] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[warn] 	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[warn] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
[warn] 	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
[warn] 	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
[warn] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
[warn] 	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
[warn] 	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
[warn] 	at sbt.inc.Incremental$.compile(Incremental.scala:71)
[warn] 	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
[warn] 	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
[warn] 	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
[warn] 	at sbt.Compiler$.compile(Compiler.scala:155)
[warn] 	at sbt.Compiler$.compile(Compiler.scala:141)
[warn] 	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:913)
[warn] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
[warn] 	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
[warn] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[warn] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[warn] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[warn] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[warn] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[warn] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[warn] 	at sbt.Execute.work(Execute.scala:237)
[warn] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[warn] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[warn] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[warn] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[warn] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[warn] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[warn] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[warn] 	at java.lang.Thread.run(Thread.java:748)
```

seems to be caused by this bizarre but valid line of code
```scala
  def defaultValue(fieldType: Type) = fieldType match {
    case typ if typ =:= typeOf[String] => q"""""""" // The empty string
    // etc.
  }
```
I presume that this is because there is no case for this in `emitContents` [here](https://github.com/scalameta/scalameta/blob/master/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala#L230)
```scala
        numStartQuotes match {
          case 1 => emitStart(curr.offset - 1); emitContents(); emitEnd(curr.offset - 1)
          case 2 => emitStart(curr.offset); curr.offset += 1; emitContents(); emitEnd(curr.offset - 1)
          case n if 3 <= n && n < 6 => emitStart(curr.offset - 3); emitContents(); emitEnd(curr.offset - 3)
          case 6 => emitStart(curr.offset - 3); emitContents(); emitEnd(curr.offset - 3)
        }
```

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce with this minimal example 
```
ollie-scalameta@ "q\"\"\"\"\"\"\"\"".parse[Term].get
scala.MatchError: 8 (of class java.lang.Integer)
  scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:234)
```

Nice job tracking down the root of the bug, I believe you are correct that https://github.com/scalameta/scalameta/blob/master/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala#L230 is the culprit.

**Comment by TF2274** [comment]
I am able to reproduce this with a similar example as well:
`s"""", """"`

The above snippet was used in a mkstring call. The idea was:
`Seq("dog", "cat", "bird").mkstring(s""""""", s"""", """", s""""""")` would come out literally as the string (including quotes): `"dog", "cat", "bird"`.
The scala code is valid.

**Comment by sjrd** [comment]
This seems to also happen in [this file](https://github.com/scala-js/scala-js/blob/5ddfc6493e368ae266b53240820a3cf765ab3dfc/ir/src/test/scala/org/scalajs/ir/PrintersTest.scala) in the Scala.js repo. It sends Metals into infinite loops trying to compile `irJS-test`, failing, retrying, etc.

**If someone could point me in the right direction regarding where to write a test and how to run it, I'm willing to contribute the fix.**

**Comment by olafurpg** [comment]
A test for this issue can be added in the `LitSuite` here https://github.com/scalameta/scalameta/blob/7dad5db172f12e535bfb463168b4d0a21c298a4c/tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala#L102

You can add a new test case with the name `#1382` matching this issue number. You can run that individual test case from the sbt shell with the following command
```
> testsJVM/testOnly scala.meta.tests.parsers.LitSuite -- -z #1382
```
It would be great to have this bug fixed!

**Comment by sjrd** [comment]
@olafurpg Thanks! There it is: #1904.
