### ISSUE TITLE
unsupported symbol NoSymbol

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1435]
While running metacp in the akka-stream module in the akka build I hit on the following errors
```
error: can't convert /Users/ollie/dev/akka/akka-stream/target/classes/akka/stream/javadsl/SubFlow.class
java.lang.RuntimeException: unsupported symbol NoSymbol
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.scalacp.Scalacp$.sowner(Scalacp.scala:366)
	at scala.meta.internal.scalacp.Scalacp$.ssymbol(Scalacp.scala:72)
	at scala.meta.internal.scalacp.Scalacp$.sowner(Scalacp.scala:353)
	at scala.meta.internal.scalacp.Scalacp$.ssymbol(Scalacp.scala:72)
	at scala.meta.internal.scalacp.Scalacp$.$anonfun$stpe$10(Scalacp.scala:277)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
...
error: can't convert /Users/ollie/dev/akka/akka-stream/target/classes/akka/stream/javadsl/SubSource.class
java.lang.RuntimeException: unsupported symbol NoSymbol
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.scalacp.Scalacp$.sowner(Scalacp.scala:366)
	at scala.meta.internal.scalacp.Scalacp$.ssymbol(Scalacp.scala:72)
	at scala.meta.internal.scalacp.Scalacp$.sowner(Scalacp.scala:353)
	at scala.meta.internal.scalacp.Scalacp$.ssymbol(Scalacp.scala:72)
	at scala.meta.internal.scalacp.Scalacp$.$anonfun$stpe$10(Scalacp.scala:277)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
```

The corresponding source files are written in scala (despite the javadsl package name) https://github.com/akka/akka/blob/ab701e98be79c8780204fce6eca8d904b4b6b589/akka-stream/src/main/scala/akka/stream/javadsl/SubFlow.scala

**Comment by olafurpg** [comment]
To reproduce
```
alias metacp='coursier launch org.scalameta:metacp_2.12:3.5.0-72-74924a4a-SNAPSHOT -r sonatype:snapshots --'
unzip subsource.zip
metacp javadsl
```

[subsource.zip](https://github.com/scalameta/scalameta/files/1806880/subsource.zip)

**Comment by olafurpg** [comment]
Even easier reproduction:
```
  val akkaStream211 = Library("com.typesafe.akka", "akka-stream_2.11", "2.5.9")
```
we already test akka-testkit for 2.12 in our test suite, but not the 2.11 artifacts.

**Comment by olafurpg** [comment]
I have a reproduction here https://github.com/scalameta/scalameta/compare/master...olafurpg:nosymbol?expand=1 but I'm not sure how best what the best way to fix this is. Could you take a look @xeno-by ?

**Comment by olafurpg** [comment]
I thought for a moment that using 2.12 scalap to analyze 2.11 classpaths was the culprit but I'm able to reproduce the problem with metacp_2.11 as well.

**Comment by xeno-by** [comment]
Confirming that I can reproduce. Will take a look.
