### ISSUE TITLE
Stackoverflow with semanticdb PrinterOps

### ISSUE THREAD

**Issue by rtfpessoa** [scalameta/scalameta#1514]
I am getting this while sbt-scalafix generates semanticdb. Any ideas what it can be?

```
java.lang.StackOverflowError
        at scala.LowPriorityImplicits.genericWrapArray(Predef.scala:486)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:41)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter.printThis(Printers.scala:310)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:767)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.render(PrinterOps.scala:162)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.resolveSelect(PrinterOps.scala:180)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.resolveSelect(PrinterOps.scala:176)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:796)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:439)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:745)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:106)
        at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:106)
        at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:96)
        at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:106)
        at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:439)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:745)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:413)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:877)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter$$anonfun$printColumn$2.apply(Printers.scala:102)
        at scala.reflect.internal.Printers$TreePrinter$$anonfun$printColumn$2.apply(Printers.scala:102)
        at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:96)
        at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:97)
        at scala.reflect.internal.Printers$TreePrinter.printColumn(Printers.scala:102)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printColumn(PrinterOps.scala:244)
        at scala.reflect.internal.Printers$TreePrinter.printBlock(Printers.scala:315)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:667)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$processTreePrinting$6$$anonfun$apply$mcV$sp$2.apply$mcV$sp(PrinterOps.scala:687)
        at scala.reflect.internal.Printers$TreePrinter.parenthesize(Printers.scala:136)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$processTreePrinting$6.apply$mcV$sp(PrinterOps.scala:687)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.insertBraces$1(PrinterOps.scala:679)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:686)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.render(PrinterOps.scala:162)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.resolveSelect(PrinterOps.scala:180)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.resolveSelect(PrinterOps.scala:174)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:796)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.print(PrinterOps.scala:56)
        at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:436)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.processTreePrinting(PrinterOps.scala:730)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.printTree(PrinterOps.scala:464)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:20)
        at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:17)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:17)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter.scala$meta$internal$semanticdb$PrinterOps$SyntheticCodePrinter$$super$print(PrinterOps.scala:59)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:64)
        at scala.meta.internal.semanticdb.PrinterOps$SyntheticCodePrinter$$anonfun$print$1.apply(PrinterOps.scala:56)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
```

**Comment by olafurpg** [comment]
Thanks for reporting! Have you tried bumping up the stack size? Some libraries generate a large amounts of code via implicits+macros.

**Comment by rtfpessoa** [comment]
I tried to increase Xms to `-Xms5g` and still does not work.

This project has quite some macros :(

I guess there is not much that can be done here?

**Comment by olafurpg** [comment]
Wow that does indicate there's infinite recursion. You can disable
synthetics with the scalac option -P:semanticdb:synthetics:none that should
be fine as long as you don't use the NoInfer rule in scalafix.

Are you able to provide a single file reproduction?

**Comment by rtfpessoa** [comment]
I am only getting this for the two biggest projects we have. They both have quite some macro usage.

Do you have any tips on how to check the file where this might be happening?

Also, `-P:semanticdb:synthetics:none` skipped the issue for now.

**Comment by olafurpg** [comment]
> Do you have any tips on how to check the file where this might be happening?

The plugin reports the culprit file for non-fatal exceptions but SO is propagated up, I don't it would be wise to change that. Glad the workaround skips the issue, we are considering disabling synthetics by default since they are of limited utility, are unspecified and add non-trivial compile overhead.

**Comment by rtfpessoa** [comment]
Then I guess we can close this. Thanks for your help.
