### ISSUE TITLE
Metacp: the process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1521]
The scalafix CI is failing on Windows due to https://ci.appveyor.com/project/scalacenter/scalafix/build/265#L1019
```
[info] scalafix.tests.core.PrettyTypeSuite *** ABORTED *** (0 milliseconds)
[info]   java.nio.file.FileSystemException: C:\Users\appveyor\AppData\Local\semanticdb\cache\3.7.4\rt-CE076AE93B691787B65675073EDA8962.jar: The process cannot access the file because it is being used by another process.
[info]   at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[info]   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[info]   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[info]   at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:376)
[info]   at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[info]   at java.nio.file.Files.move(Files.java:1395)
[info]   at scala.meta.internal.metacp.Main.createCachedJar$1(Main.scala:60)
[info]   at scala.meta.internal.metacp.Main.$anonfun$process$2(Main.scala:80)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:929)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:929)
```
It's fine to ignore this error since this indicates the file already exists.

**Comment by olafurpg** [comment]
I just realized that instead of overwriting on move, we should bail out and use the existing file. This should both the number of concurrency issues we've seen and also make the logic around moving files simpler.
