### ISSUE TITLE
Figure out how to deal with shading

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1675]
Apparently, shading tools update JVM metadata, but don't touch ScalaSignatures. Consequently, shaded jars may end up having a bunch of missing symbols in ScalaSignatures. Previously, that wasn't a problem, but with the introduction of a mandatory dependency classpath in metacp, this becomes a blocker.

**Comment by olafurpg** [comment]
It sounds like OSGi might be able to help us for this problem but after reading up on OSGi for 30 minutes I still have no clue how to use it. The scala-compiler jar uses OSGi but I can't see in MANIFEST.MF that it declares the rewrite rules.

Most shading tools use jarjar which supports a `<rulesFile>` text file https://github.com/shevek/jarjar#using-from-the-command-line which has the following syntax
```
rule <pattern> <result>
zap <pattern>
keep <pattern>
```

> The standard rule (rule) is used to rename classes. All references to the renamed classes will also be updated. If a class name is matched by more than one rule, only the first one will apply.
> `<pattern>` is a class name with optional wildcards. ** will match against any valid class name substring. To match a single package component (by excluding . from the match), a single * may be used instead.
> `<result>` is a class name which can optionally reference the substrings matched by the wildcards. A numbered reference is available for every * or ** in the <pattern>, starting from left to right: `@1`, `@2`, etc. A special `@0` reference contains the entire matched class name.
> The zap rule causes any matched class to be removed from the resulting jar file. All zap rules are processed before renaming rules.

One solution is that metacp supports the flag `--jarjar-rules <path>`. It would be awesome if jar files that use shading contained the rules file under `META-INF` but there doesn't seem to be an established convention for that.

That still leaves us with a problem, what do we do with references to symbols that have been "zapped"?

**Comment by olafurpg** [comment]
FWIW, the scala-compiler OSGi MANIFEST.MF declares an optional `Import-Package` on `jline.*` and ant

```
Import-Package:
  jline;resolution:=optional,
  jline.console;resolution:=optional,
  jline.console.completer;resolution:=optional,
  jline.console.histor y;resolution:=optional,
  org.apache.tools.ant;resolution:=optional,
  org.ap ache.tools.ant.taskdefs;resolution:=optional,
  org.apache.tools.ant.types ;resolution:=optional,
  org.apache.tools.ant.util;resolution:=optional,
```

These are the missing symbol that we encounter when processing `scala-compiler`.

**Comment by olafurpg** [comment]
Encountered another problematic jar, `org.scalatest:scalatest`. The classfiles seem to depend on junit/mockito/easymock/jmock/ant even if the scalatest maven module does not depend on those. The JVM loads classes lazily so there is guarantee that all external references are contained in the transitive dependencies.

**Comment by xeno-by** [comment]
The problem with `scalatest` is that these dependencies are `optional`, so they aren't fetched by default.

**Comment by olafurpg** [comment]
This is no longer an issue in Scalafix since we use `GlobalSymbolTable` without caching or indexing.

**Comment by olafurpg** [comment]
This is no longer an issue in Scalafix since we use `GlobalSymbolTable` without caching or indexing.

**Comment by olafurpg** [comment]
I propose to close this ticket as "Fixed" since `GlobalSymbolTable` respected shadowed classpath definitions the same way as scala-compiler.

**Comment by xeno-by** [comment]
This is still a problem for Rsc, which uses Metacp to eagerly preprocess classpaths. Not a blocker for 4.0 though.

**Comment by jtjeferreira** [comment]
I think I am hitting this problem.

I am getting this error:
```
scalafix.internal.v1.FileException: unexpected error processing file /xxxx/Client.scala
Caused by: scala.meta.internal.classpath.MissingSymbolException: missing symbol: org.jctools
    at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.descriptor(SymbolOps.scala:119)
    at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:18)
    at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:25)
    at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:185)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.owner(SymbolOps.scala:58)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:18)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:25)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:185)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.owner(SymbolOps.scala:58)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:18)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:25)
	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:185)
	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.loop$1(TypeOps.scala:22)
	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.toSemanticTpe(TypeOps.scala:94)
	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.loop$2(TypeOps.scala:108)
	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.toSemanticSig(TypeOps.scala:139)
	at scala.meta.internal.scalacp.SymbolInformationOps$XtensionGSymbolSSymbolInformation.sig(SymbolInformationOps.scala:164)
	at scala.meta.internal.scalacp.SymbolInformationOps$XtensionGSymbolSSymbolInformation.toSymbolInformation(SymbolInformationOps.scala:251)
	at scala.meta.internal.scalacp.Scalacp.sinfos(Scalacp.scala:32)
	at scala.meta.internal.scalacp.Scalacp.$anonfun$parse$1(Scalacp.scala:20)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at scala.meta.internal.scalacp.Scalacp.parse(Scalacp.scala:19)
	at scala.meta.internal.scalacp.Scalacp$.parse(Scalacp.scala:50)
	at scala.meta.internal.metacp.ClassfileInfos$.fromClassNode(ClassfileInfos.scala:46)
	at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:40)
	at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:69)
	at scalafix.internal.v1.InternalSemanticDoc.info(InternalSemanticDoc.scala:71)
	at scalafix.v1.SemanticDocument.info(SemanticDocument.scala:38)
	at scalafix.v1.Symbol.info(Symbol.scala:21)
	at scalafix.internal.scaluzzi.MissingFinal.isSealed$1(MissingFinal.scala:13)
	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$2(MissingFinal.scala:17)
	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$2$adapted(MissingFinal.scala:17)
	at scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)
	at scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)
	at scala.collection.immutable.List.exists(List.scala:89)
	at scalafix.internal.scaluzzi.MissingFinal.leaksSealedParent$1(MissingFinal.scala:17)
	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$7(MissingFinal.scala:39)
	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$7$adapted(MissingFinal.scala:34)
	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:67)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
	at scalafix.internal.scaluzzi.MissingFinal.collect(MissingFinal.scala:78)
	at scalafix.internal.scaluzzi.MissingFinal.fix(MissingFinal.scala:34)
	at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:75)
	at scala.collection.immutable.List.map(List.scala:290)
	at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:73)
	at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:233)

```

I pinpointed this to the library `Kamon` which shades `org.jctools` (https://github.com/kamon-io/Kamon/blob/e093cabc6685ee62595c5d912f126b97590523a6/build.sbt#L34)

There is any workaround? Or there is anything that I can contribute the Kamon project to "fix" the shading?
