### ISSUE TITLE
Parser bug on akka codebase

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1710]
with scalameta 2.1.7:

https://github.com/akka/akka/blob/v2.5.14/akka-remote/src/test/scala/akka/remote/DaemonicSpec.scala

```
error: Failed to fix /home/gui/akka/akka-remote/src/test/scala/akka/remote/DaemonicSpec.scala
scala.MatchError: *[Set] (of class scala.meta.Term$ApplyType$TermApplyTypeImpl)
        at fix.Stable212Base$$anonfun$5.$anonfun$applyOrElse$3(Stable212Base.scala:245)
        at scala.Option.map(Option.scala:146)
        at fix.Stable212Base$$anonfun$5.applyOrElse(Stable212Base.scala:244)
        at fix.Stable212Base$$anonfun$5.applyOrElse(Stable212Base.scala:236)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:32)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
        at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
```

**Comment by MasseGuillaume** [comment]
Ops, this is related to my codebase.
