### ISSUE TITLE
Syntax error when generating semanticdb synthetic

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1733]
```
error: Failed to fix /home/gui/akka/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala
<input>:1: error: ] expected but with found
*[Buffer[Entry], akka.cluster.ddata.ORMap.AtomicDeltaOp[_1,_2] forSome { type _1; type _2 <: akka.cluster.ddata.ReplicatedDelta; type _1 >: _1; type _2 >: _2 <: akka.cluster.ddata.ReplicatedData } with Product{}, Vector[DeltaOp]](scala.collection.immutable.Vector.canBuildFrom[akka.cluster.ddata.ORMap.AtomicDeltaOp[_1,_2] forSome { type _1; type _2 <: akka.cluster.ddata.ReplicatedDelta; type _1 >: _1; type _2 >: _2 <: akka.cluster.ddata.ReplicatedData } with Product{}])
                                                                                                                                                                                                     ^
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
        at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:18)
        at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:18)
        at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
        at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:399)
        at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:405)
        at scala.meta.internal.parsers.ScalametaParser.inBrackets(ScalametaParser.scala:338)
        at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typeArgs(ScalametaParser.scala:943)
        at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typeArgs$(ScalametaParser.scala:943)
        at scala.meta.internal.parsers.ScalametaParser$outPattern$.typeArgs(ScalametaParser.scala:2318)
        at scala.meta.internal.parsers.ScalametaParser.exprTypeArgs(ScalametaParser.scala:2341)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExprRest$2(ScalametaParser.scala:1912)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:377)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExprRest$1(ScalametaParser.scala:1912)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:377)
        at scala.meta.internal.parsers.ScalametaParser.simpleExprRest(ScalametaParser.scala:1901)
        at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr$1(ScalametaParser.scala:1898)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:377)

```

See:
https://github.com/akka/akka/blob/b72312d428223156c10130e19f921e8ae5f336b6/akka-distributed-data/src/main/scala/akka/cluster/ddata/protobuf/ReplicatedDataSerializer.scala#L524-L534

on scalameta 2.1.7

**Comment by olafurpg** [comment]
Synthetics have been revamped entirely since v2.1.7 and no longer rely on the syntax parser. Please reopen if you are able to reproduce with the new synthetics in v4.
