### ISSUE TITLE
q"(i: Int) => 42" doesn't work

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#178]
```
11:01 ~/Projects/core/sandbox (master)$ parse '(i: Int) => 42'
// Scala source: /var/folders/n4/39sn1y_d1hn3qjx6h1z3jk8m0000gn/T/tmpVj8xdZ
scala.meta.ParseException: ; expected but right arrow found at 9..11
	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:13)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:19)
	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:14)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:19)
	at scala.meta.internal.parsers.Parser.syntaxErrorExpected(Parsers.scala:478)
	at scala.meta.internal.parsers.Parser.accept(Parsers.scala:484)
	at scala.meta.internal.parsers.Parser.acceptStatSep(Parsers.scala:497)
	at scala.meta.internal.parsers.Parser.acceptStatSepOpt(Parsers.scala:501)
	at scala.meta.internal.parsers.Parser.statSeq(Parsers.scala:2699)
	at scala.meta.internal.parsers.Parser$$anonfun$parseStat$1.apply(Parsers.scala:46)
	at scala.meta.internal.parsers.Parser$$anonfun$parseStat$1.apply(Parsers.scala:46)
	at scala.meta.internal.parsers.Parser.parseRule(Parsers.scala:36)
	at scala.meta.internal.parsers.Parser.parseStat(Parsers.scala:46)
	at scala.meta.syntactic.Api$Parse$$anonfun$parseStat$1.apply(Api.scala:40)
	at scala.meta.syntactic.Api$Parse$$anonfun$parseStat$1.apply(Api.scala:40)
	at scala.meta.syntactic.Api$Parse$$anon$1.apply(Api.scala:39)
	at scala.meta.syntactic.Api$Parse$$anon$1.apply(Api.scala:39)
	at scala.meta.syntactic.Api$XtensionInputLike.parse(Api.scala:60)
	at scala.meta.tools.Metac$.delayedEndpoint$scala$meta$tools$Metac$1(Metac.scala:106)
	at scala.meta.tools.Metac$delayedInit$body.apply(Metac.scala:9)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at scala.App$class.main(App.scala:76)
	at scala.meta.tools.Metac$.main(Metac.scala:9)
	at scala.meta.tools.Metac.main(Metac.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by Dveim** [comment]
Isn't this issue closed?

**Comment by xeno-by** [comment]
Indeed it is now.
