### ISSUE TITLE
Semanticdb files not generated when running in IntelliJ

### ISSUE THREAD

**Issue by violence102** [scalameta/scalameta#1785]
When I try to run a code with semanticdb plugin it fails on compilation step (scalac) with the following error:
`Error:scalac: failed to generate semanticdb for C:\workspace\semanticdb-example\example\src\main\scala\example\Domain.scala:
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/workspace/semanticdb-example/example/src/main/scala/example/Domain.scala.semanticdb
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at scala.meta.io.AbsolutePath.resolve(AbsolutePath.scala:27)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPaths$.toSemanticdb(SemanticdbPaths.scala:50)
	at scala.meta.internal.semanticdb.scalac.package$XtensionSchemaTextDocument.write(package.scala:15)
	at scala.meta.internal.semanticdb.scalac.package$XtensionSchemaTextDocument.save(package.scala:27)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:65)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:75)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:83)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
`

**Comment by 4lex1v** [comment]
Left a comment in https://github.com/scalameta/scalameta/issues/1835#issuecomment-488350961 Having the same issue with plain SBT.

**Comment by jameskoch** [comment]
I can replicate this in IntelliJ but not in SBT. Tried a few different versions, but currently on IntelliJ 2019.1, Scala 2.12.8, SBT 1.2.8, scalameta@HEAD.

Aside - I see a ton of unit test failures in `sbt testsJVM/test` on Windows. Am I in for a world of pain trying to run semanticdb (really, scalafix) on Windows?

Will try to submit a PR; will be my first here :)

Adding some debugging, run under IntelliJ, I see SemanticdbPaths.toSemanticdb https://github.com/scalameta/scalameta/blob/41e72d74ada31cbbc399ca058496d34f1200b4e4/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPaths.scala#L50 encountering the values:
targetroot = C:\Users\Administrator\Desktop\. 
semanticdbPrefix = META-INF\semanticdb
doc.uri = file:///C:/Users/Administrator/IdeaProjects/Scala2128Sbt128/src/main/scala/Test.scala

**Comment by olafurpg** [comment]
> Am I in for a world of pain trying to run semanticdb (really, scalafix) on Windows?

We run the Scalameta, SemanticDB and Scalafix test suites on Windows for every pull request. It should work fine, this bug looks related to your other interesting observation

> The error goes away if I enable the non-default IntelliJ option "Use project home as compile server working directory".

Nice debugging! What happens if you add following compiler option in build.sbt?

```scala
scalacOptions += s"-P:semanticdb:sourceroot:${baseDirectory.in(ThisBuild).value}"
````

**Comment by jameskoch** [comment]
That `scalacOptions ` resolves the issue as well.

**Comment by tgodzik** [comment]
Let's reopen this if it's still relevant.
