### ISSUE TITLE
PrettyType.TypeToTreeError on Symbol inside a package object

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1813]
When I run scalameta on the following repo: https://github.com/masseGuillaume/meta-package

I get a `scalafix.internal.util.PrettyType$TypeToTreeError`.

To reproduce:

```bash
git clone git@github.com:MasseGuillaume/meta-package.git
cd meta-package
sbt scalafix
```

obtained:

```bash
scalafix.internal.v1.FileException: unexpected error processing file /home/gui/foos/meta-package/src/main/scala/foo/json/protocol.scala
Caused by: scalafix.internal.util.PrettyType$TypeToTreeError: SymbolInformation(foo/bar/package.A#,SCALA,CLASS,128,A,ClassSignature(Some(Scope(List(),List())),List(TypeRef(Empty,scala/AnyRef#,List()), TypeRef(Empty,scala/Product#,List()), TypeRef(Empty,scala/Serializable#,List())),Empty,Some(Scope(List(foo/bar/package.A#v., foo/bar/package.A#`<init>`()., foo/bar/package.A#copy()., foo/bar/package.A#copy$default$1()., foo/bar/package.A#productPrefix()., foo/bar/package.A#productArity()., foo/bar/package.A#productElement()., foo/bar/package.A#productIterator()., foo/bar/package.A#canEqual()., foo/bar/package.A#hashCode()., foo/bar/package.A#toString()., foo/bar/package.A#equals().),List()))),List(),PublicAccess())
	at scalafix.internal.util.PrettyType.fail(PrettyType.scala:421)
	at scalafix.internal.util.PrettyType.toTypeRef(PrettyType.scala:490)
	at scalafix.internal.util.PrettyType.toType(PrettyType.scala:519)
	at scalafix.internal.util.PrettyType.$anonfun$toType$1(PrettyType.scala:503)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:455)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:309)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:307)
	at scala.collection.AbstractIterator.to(Iterator.scala:1425)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:293)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:293)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1425)
	at scalafix.internal.util.PrettyType.targs$1(PrettyType.scala:499)
	at scalafix.internal.util.PrettyType.toType(PrettyType.scala:526)
	at scalafix.internal.util.PrettyType$.toType(PrettyType.scala:36)
	at scalafix.internal.rule.ExplicitResultTypes.unsafeToType(ExplicitResultTypes.scala:82)
	at scalafix.internal.rule.ExplicitResultTypes.toType(ExplicitResultTypes.scala:91)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$2(ExplicitResultTypes.scala:109)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$1(ExplicitResultTypes.scala:108)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.defnType$1(ExplicitResultTypes.scala:107)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$9(ExplicitResultTypes.scala:130)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$7(ExplicitResultTypes.scala:127)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$5(ExplicitResultTypes.scala:123)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.scalafix$internal$rule$ExplicitResultTypes$$fix$1(ExplicitResultTypes.scala:122)
	at scalafix.internal.rule.ExplicitResultTypes$$anonfun$fix$15.applyOrElse(ExplicitResultTypes.scala:180)
	at scalafix.internal.rule.ExplicitResultTypes$$anonfun$fix$15.applyOrElse(ExplicitResultTypes.scala:177)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:32)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:33)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI.collect(Api.scala:36)
	at scalafix.internal.rule.ExplicitResultTypes.fix(ExplicitResultTypes.scala:177)
	at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:55)
	at scala.collection.immutable.List.map(List.scala:282)
	at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:53)
	at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:196)
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a scalafix issue so it should be reported there instead :)

The `ExplicitResultTypes` rule is not officially supported due to having known issues. It's not documented on the website and doesn't appear in tab completions. I think the most likely "fix" for this issue will be to remove the implementation entirely from the codebase, but that will require refactoring several tests.

**Comment by MasseGuillaume** [comment]
Ah ops I missed the scalafix part in the stacktrace :p.
