### ISSUE TITLE
Unable to compile JetBrains's intellij-scala

### ISSUE THREAD

**Issue by fikovnik** [scalameta/scalameta#1833]
I checked out the code from `https://github.com/JetBrains/intellij-scala`, tag: `2018.3.5.5`.

It compiles file, but adding semanticdb plugin fails the build with the following:

```
...
[info] Compiling 1169 Scala sources and 63 Java sources to /home/krikava/Research/Projects/scala-implicits-analysis/corpora/top100/all-projects/JetBrains--intellij-scala/scala/scala-impl/target/scala-2.12/test-classes...
java.lang.UnsupportedOperationException: Position.point on NoPosition
        at scala.reflect.internal.util.Position.fail(Position.scala:17)
        at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:95)
        at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:90)
        at scala.reflect.internal.Positions.wrappingPos(Positions.scala:42)
        at scala.reflect.internal.Positions.wrappingPos$(Positions.scala:38)
        at scala.reflect.internal.SymbolTable.wrappingPos(SymbolTable.scala:18)
        at scala.reflect.internal.Positions.wrappingPos(Positions.scala:37)
        at scala.reflect.internal.Positions.wrappingPos$(Positions.scala:37)
        at scala.reflect.internal.SymbolTable.wrappingPos(SymbolTable.scala:18)
        at scala.reflect.internal.TreeGen.mkTemplate(TreeGen.scala:417)
        at scala.reflect.internal.ReificationSupport$ReificationSupportImpl$SyntacticClassDef$.apply(ReificationSupport.scala:346)
        at org.scalameta.paradise.reflect.TreeInfo$ParadiseTreeInfo$PatchedSyntacticClassDef$.apply(TreeInfo.scala:193)
        at org.scalameta.paradise.reflect.TreeInfo$ParadiseTreeInfo.$anonfun$getAnnotationZippers$1(TreeInfo.scala:64)
        at scala.collection.immutable.List.map(List.scala:283)
        at org.scalameta.paradise.reflect.TreeInfo$ParadiseTreeInfo.loop$1(TreeInfo.scala:53)
        at org.scalameta.paradise.reflect.TreeInfo$ParadiseTreeInfo.getAnnotationZippers(TreeInfo.scala:171)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbol(Namers.scala:195)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbol$(Namers.scala:179)
        at org.scalameta.paradise.typechecker.Namers$$anon$3.finishSymbol(Namers.scala:12)
        at org.scalameta.paradise.typechecker.Namers$Namer.dispatch$1(Namers.scala:33)
        at org.scalameta.paradise.typechecker.Namers$Namer.enterSym(Namers.scala:40)
        at org.scalameta.paradise.typechecker.Namers$Namer.enterSym$(Namers.scala:21)
        at org.scalameta.paradise.typechecker.Namers$$anon$3.enterSym(Namers.scala:12)
        at org.scalameta.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterSym(AnalyzerPlugins.scala:49)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$15.custom(AnalyzerPlugins.scala:461)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.$anonfun$invoke$3(AnalyzerPlugins.scala:403)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:403)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym(AnalyzerPlugins.scala:455)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym$(AnalyzerPlugins.scala:453)
        at org.scalameta.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsEnterSym(HijackAnalyzer.scala:31)
        at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:261)
        at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$enterSyms$1(Namers.scala:477)
        at scala.tools.nsc.typechecker.Namers$Namer.enterSyms(Namers.scala:476)
        at org.scalameta.paradise.typechecker.Namers$Namer.$anonfun$finishSymbolNotExpandee$1(Namers.scala:234)
        at org.scalameta.paradise.typechecker.Namers$Namer.savingLock$1(Namers.scala:228)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbolNotExpandee(Namers.scala:232)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbolNotExpandee$(Namers.scala:224)
        at org.scalameta.paradise.typechecker.Namers$$anon$3.finishSymbolNotExpandee(Namers.scala:12)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbol(Namers.scala:196)
        at org.scalameta.paradise.typechecker.Namers$Namer.finishSymbol$(Namers.scala:179)
        at org.scalameta.paradise.typechecker.Namers$$anon$3.finishSymbol(Namers.scala:12)
        at org.scalameta.paradise.typechecker.Namers$Namer.dispatch$1(Namers.scala:33)
        at org.scalameta.paradise.typechecker.Namers$Namer.enterSym(Namers.scala:40)
        at org.scalameta.paradise.typechecker.Namers$Namer.enterSym$(Namers.scala:21)
        at org.scalameta.paradise.typechecker.Namers$$anon$3.enterSym(Namers.scala:12)
        at org.scalameta.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterSym(AnalyzerPlugins.scala:49)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$15.custom(AnalyzerPlugins.scala:461)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.$anonfun$invoke$3(AnalyzerPlugins.scala:403)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:403)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym(AnalyzerPlugins.scala:455)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym$(AnalyzerPlugins.scala:453)
        at org.scalameta.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsEnterSym(HijackAnalyzer.scala:31)
        at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:261)
        at scala.tools.nsc.typechecker.Analyzer$namerFactory$$anon$1.apply(Analyzer.scala:43)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
        at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
        at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
        at sbt.inc.Incremental$.compile(Incremental.scala:71)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:927)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:918)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:916)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (scala-impl/test:compileIncremental) java.lang.UnsupportedOperationException: Position.point on NoPosition
[error] Total time: 3 s, completed Feb 8, 2019 11:48:47 PM
```

I used the following [sbt plugin](https://github.com/PRL-PRG/scala-implicits-analysis/blob/master/sbt-plugins/src/main/scala-sbt-0.13/cz/cvut/fit/prl/scala/implicits/sbt/SemanticdbCommandPlugin.scala) to compile with semanticdb. It is based on Olaf's code.

Scalameta version is: 4.1.0
Scala version is: 2.12.6
SBT version is: 0.13.17

**Comment by olafurpg** [comment]
Thanks for reporting! Can you reproduce with the latest SemanticDB version?

**Comment by fikovnik** [comment]
Just checked with 4.1.4 and it is the same.

**Comment by olafurpg** [comment]
I see the stack trace points to scalameta/paradise, which is unmaintained and has been archived for a long time. I'm surprised if they use scalameta/paradise outside tests, you might be able to remove it or replace it scalamacros/paradise. 

Closing as wontfix.
