### ISSUE TITLE
The semanticdb-scalac compiler plugin throws NullPointerException when generating the Semantic DB

### ISSUE THREAD

**Issue by Atry** [scalameta/scalameta#1851]
```
[error] failed to generate semanticdb for /home/travis/build/Atry/Binding.scala/fxml/.jvm/src/test/scala/com/thoughtworks/binding/FxmlSample.scala:
[error] java.lang.NullPointerException
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$tryFindMtree$7(TextDocumentOps.scala:398)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$tryFindMtree$7$adapted(TextDocumentOps.scala:396)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.tryFindMtree(TextDocumentOps.scala:396)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:655)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1270)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1251)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1239)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1364)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1320)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$traverse$1(TextDocumentOps.scala:595)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$traverse$1$adapted(TextDocumentOps.scala:593)
[error] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:593)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1268)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1243)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1239)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1364)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1362)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:660)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:67)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:77)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] [0m	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] failed to generate semanticdb for /home/travis/build/Atry/Binding.scala/fxml/.jvm/src/test/scala/com/thoughtworks/binding/fxmlTest.scala:
[error] java.lang.NullPointerException
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$tryFindMtree$7(TextDocumentOps.scala:398)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$tryFindMtree$7$adapted(TextDocumentOps.scala:396)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.tryFindMtree(TextDocumentOps.scala:396)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:655)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1270)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1245)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1239)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1364)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1320)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$traverse$1(TextDocumentOps.scala:595)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.$anonfun$traverse$1$adapted(TextDocumentOps.scala:593)
[error] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:593)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1270)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] [0m	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
[error] 	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1320)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
[error] 	at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1268)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1366)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1243)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1239)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1364)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)0m
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:187)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
[error] 	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
[error] 	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
[error] 	at scala.reflect.internal.Trees.itraverse(Trees.scala:1362)
[error] 	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1236)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:27)
[error] 	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
[[0merror] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument$traverser$3$.traverse(TextDocumentOps.scala:657)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:660)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:67)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:77)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] 0m	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[warn] 8 warnings found
[error] two errors found
```

semanticdb-scalac version: 4.1.5
Source Code: https://github.com/Atry/Binding.scala/blob/semanticdb-crash/fxml/.jvm/src/test/scala/com/thoughtworks/binding/FxmlSample.scala
Logs: https://travis-ci.org/Atry/Binding.scala/jobs/512911260

**Comment by olafurpg** [comment]
Thanks for reporting and providing a reproduction! It seems we're hitting on unexpected `Tree.tpe == null` that I suspect might be related to mixing imports and XML literals. It should be an easy fix to at least guard against those nulls.
