### ISSUE TITLE
Exception while unquoting names like '$x'

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#190]
Here is an example: (note a space in second line)
Also second line probably should result in "y", not "$y".

```
scala> val $y = q"y"
$y: scala.meta.internal.ast.Term.Name = y

scala> q" $$y"
res2: scala.meta.internal.ast.Term.Name = $y

scala> q"$$y"
<console>:15: error: exception during macro expansion:
java.lang.UnsupportedOperationException: position-changing adjust on Token.BOF: expected 0..0, actual 1..1
    at scala.meta.syntactic.Token$BOF.adjust(Token.scala:145)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros$$anonfun$5$$anonfun$apply$1.apply(ReificationMacros.scala:169)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros$$anonfun$5$$anonfun$apply$1.apply(ReificationMacros.scala:167)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros$$anonfun$5.apply(ReificationMacros.scala:167)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros$$anonfun$5.apply(ReificationMacros.scala:104)
    at scala.collection.immutable.List.map(List.scala:273)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros.parseSkeleton(ReificationMacros.scala:104)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros.expand(ReificationMacros.scala:64)
    at scala.meta.internal.quasiquotes.ast.ReificationMacros.apply(ReificationMacros.scala:61)

       q"$$y"
       ^
```

**Comment by xeno-by** [comment]
Fixed in v2.0.
