### ISSUE TITLE
Unable to use latest metac

### ISSUE THREAD

**Issue by ckipp01** [scalameta/scalameta#2023]
When attempting to follow the semanticdb guide on the [Scalameta site](https://scalameta.org/docs/semanticdb/guide.html) it seems that metac isn't working.

If you install the latest metac via `cs install metac` or use the alias that is described on the site on the following code:

`Test.scala`
```
object Test {
  def main(args: Array[String]): Unit = {
    println("hello world")
  }
}
```

You will then see the following.

```
❯ metac Test.scala
error: error while loading Object, Missing dependency 'object scala.native in compiler mirror', required by /Users/ckipp/.sdkman/candidates/java/8.0.242-librca/jre/lib/rt.jar(java/lang/Object.class)
error: scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:24)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$6(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:66)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:195)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:195)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:196)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:196)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyClass$lzycompute(Definitions.scala:284)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnyClass(Definitions.scala:284)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ClassTypeCompleter.complete(ClassfileParser.scala:1273)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1544)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1517)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1691)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1585)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1205)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:47)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
	at scala.tools.nsc.Driver.process(Driver.scala:68)
	at scala.meta.internal.metac.Main.$anonfun$process$3(Main.scala:31)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at scala.meta.internal.metac.Main.$anonfun$process$2(Main.scala:31)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at scala.meta.internal.metac.Main.process(Main.scala:30)
	at scala.meta.cli.Metac$.process(Metac.scala:36)
	at scala.meta.cli.Metac$.process(Metac.scala:27)
	at scala.meta.cli.Metac$.main(Metac.scala:10)
	at scala.meta.cli.Metac.main(Metac.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

**Comment by olafurpg** [comment]
Thank you for reporting! I'm able to reproduce, a workaround is to `cs install metac` and run
```
metac -usejavacp Test.scala
```

After https://github.com/coursier/apps/pull/15 is released the `-usejavacp` flag will no longer be needed.

**Comment by olafurpg** [comment]
I opened https://github.com/scalameta/scalameta/pull/2025 updating the docs to use `coursier install`. That page has quite a bit of outdated documentation about features that no longer exist, like the javac compiler plugin.

**Comment by ckipp01** [comment]
Ahhh, I didn't know the `-usejavacp` was required. Once I included that, then it works. Thanks for addressing this so quickly!
