### ISSUE TITLE
Regression in 4.3.16: fails to parse big multiline expression

### ISSUE THREAD

**Issue by japgolly** [scalameta/scalameta#2082]
I've just upgraded to Scala 2.13.3 and SemanticDB 4.3.16 and scalameta is crashing parsing code that it was happy to parse before. I've got this big, kind-of-ugly expression:

```scala
      (  validReqTypeIds("Field.fieldReqTypeRules.reqTypes",
          _.fields.customFields.valuesIterator.flatMap(_.fieldReqTypeRules.perReqType.keys))

      ∧ validTagIds("Field.fieldReqTypeRules.defaults",
        p => fields.filteredFields({ case t: CustomField.Tag => t.fieldReqTypeRules})(p.fields)
          .flatMap(_.resolutionIterator().collect { case FieldReqTypeRules.Resolution.DefaultTo(id) => id })) // HERE

      ∧ validTagIds("CustomField.Tag.tagIds",
        p => fields.filteredFields({ case t: CustomField.Tag => t.tagId})(p.fields))

      ∧ validReqTypeIds("CustomField.Implication.reqTypeIds",
          p => fields.filteredFields({ case t: CustomField.Implication => t.reqTypeId})(p.fields))

      ∧ validReqTypeIds("ApplicableTag.applicableReqTypes",
        _.tags.applicableTagIterator().flatMap(_.applicableReqTypes.reqTypes))

      ).rename("Cross-constituent refs").contramap[P](_ mapStrengthR mkRefs)
```

It now throws this exception at the line I've marked with `// HERE` above.

```
[error] error: ) expected but \n\n found
[error] 
[error] ^
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:433)
[error] 	at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:439)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inParens(ScalametaParser.scala:329)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inParensOrTupleOrUnit(ScalametaParser.scala:905)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr$3(ScalametaParser.scala:2073)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr$1(ScalametaParser.scala:2073)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2054)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2045)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2025)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$11(ScalametaParser.scala:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$1(ScalametaParser.scala:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1585)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$2(ScalametaParser.scala:3994)
[error] 	at scala.meta.internal.parsers.ScalametaParser.stat(ScalametaParser.scala:3855)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockStatSeq(ScalametaParser.scala:3994)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$block$1(ScalametaParser.scala:2244)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.block(ScalametaParser.scala:2244)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockExpr$2(ScalametaParser.scala:2239)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:344)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockExpr$1(ScalametaParser.scala:2237)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockExpr(ScalametaParser.scala:2236)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr$1(ScalametaParser.scala:2076)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2054)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2045)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2025)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$11(ScalametaParser.scala:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$1(ScalametaParser.scala:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1585)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1556)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$funDefRest$1(ScalametaParser.scala:3401)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.funDefRest(ScalametaParser.scala:3345)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$funDefExtRest$1(ScalametaParser.scala:3212)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.funDefExtRest(ScalametaParser.scala:3208)
[error] 	at scala.meta.internal.parsers.ScalametaParser.funDefOrDclOrExtensionOrSecondaryCtor(ScalametaParser.scala:3204)
[error] 	at scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:3116)
[error] 	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:3101)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3926)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3922)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3871)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateStats(ScalametaParser.scala:3921)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateStatSeq(ScalametaParser.scala:3918)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateBody$1(ScalametaParser.scala:3788)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:344)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateBody(ScalametaParser.scala:3788)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateBodyOpt(ScalametaParser.scala:3793)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:3782)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$objectDef$1(ScalametaParser.scala:3558)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.objectDef(ScalametaParser.scala:3550)
[error] 	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3452)
[error] 	at scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:3124)
[error] 	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:3101)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3926)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:3922)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3871)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateStats(ScalametaParser.scala:3921)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateStatSeq(ScalametaParser.scala:3918)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateBody$1(ScalametaParser.scala:3788)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:344)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateBody(ScalametaParser.scala:3788)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateBodyOpt(ScalametaParser.scala:3793)
[error] 	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:3782)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$objectDef$1(ScalametaParser.scala:3558)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.objectDef(ScalametaParser.scala:3550)
[error] 	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3452)
[error] 	at scala.meta.internal.parsers.ScalametaParser.topLevelTmplDef(ScalametaParser.scala:3436)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$topStat$1.applyOrElse(ScalametaParser.scala:3890)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$topStat$1.applyOrElse(ScalametaParser.scala:3880)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3871)
[error] 	at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:3879)
[error] 	at scala.meta.internal.parsers.ScalametaParser.bracelessPackageStats$1(ScalametaParser.scala:4069)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$9(ScalametaParser.scala:4075)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4075)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4043)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4026)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:411)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:417)
[error] 	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4025)
[error] 	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4031)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$2(ScalametaParser.scala:134)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:44)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:134)
[error] 	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anon$209.apply(ScalametaParser.scala:4087)
[error] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
[error] 	at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:11)
[error] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:178)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:60)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:67)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
[error] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:77)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1626)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] 	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I can workaround this issue by doing the following:

```scala
      val workaround1 =
        validTagIds("Field.fieldReqTypeRules.defaults",
          p => fields.filteredFields({ case t: CustomField.Tag => t.fieldReqTypeRules})(p.fields)
            .flatMap(_.resolutionIterator().collect { case FieldReqTypeRules.Resolution.DefaultTo(id) => id }))

      val workaround2 =
        validTagIds("CustomField.Tag.tagIds",
          p => fields.filteredFields({ case t: CustomField.Tag => t.tagId})(p.fields))

      val workaround3 =
        validReqTypeIds("CustomField.Implication.reqTypeIds",
          p => fields.filteredFields({ case t: CustomField.Implication => t.reqTypeId})(p.fields))

      val workaround4 =
        validReqTypeIds("ApplicableTag.applicableReqTypes",
          _.tags.applicableTagIterator().flatMap(_.applicableReqTypes.reqTypes))

      (  validReqTypeIds("Field.fieldReqTypeRules.reqTypes",
          _.fields.customFields.valuesIterator.flatMap(_.fieldReqTypeRules.perReqType.keys))
      ∧ workaround1
      ∧ workaround2
      ∧ workaround3
      ∧ workaround4
      ).rename("Cross-constituent refs").contramap[P](_ mapStrengthR mkRefs)
```

**Comment by tgodzik** [comment]
We actually released 4.3.17, which should fix this issue. Could you try it out? We should most likely create the releases in the repo finally.

**Comment by japgolly** [comment]
Oh whoops. Yes, you're right. Problem gone in 4.3.17, thank you!!

> We should most likely create the releases in the repo finally.

Yeah especially with the new design, it's become misleading because on the front page Github declares that 4.3.15 is the latest. Also since they introduced the ability to Watch Releases, people don't get notified on new tags, only when you declare a tag as a release. :(

**Comment by tgodzik** [comment]
> Yeah especially with the new design, it's become misleading because on the front page Github declares that 4.3.15 is the latest. Also since they introduced the ability to Watch Releases, people don't get notified on new tags, only when you declare a tag as a release. :(

That's my bad, I should have added those releases, just totally forgot while trying to release Metals with the support for 2.13.3. I added the two releases, I will publish a new one most likely in the evening.

Anyway, thanks for finding the issues, it was super helpful! It's always better to report it even if the fix is already somewhere. Let us know if you find anything else.

**Comment by japgolly** [comment]
No worries and thanks for all your work!
