### ISSUE TITLE
`testkit/test` fails, and is not tested in CI

### ISSUE THREAD

**Issue by SethTisue** [scalameta/scalameta#2246]
in a fresh checkout:

```
sbt:scalametaRoot> testkit/test
scala.meta.tests.prettyprinters.PrettyPrinterSuite:
  + val∙x∙=∙1 0.271s
  + (_:∙Throwable)∙⇒∙1 0.042s
  + 1∙join∙(()) 0.016s
  + foo∙match{∙case∙_∙=>∙_∙=>∙false} 0.047s
scala.meta.tests.contrib.ScaladocParserProps:
  + parser does not crash 1.843s
scala.meta.tests.transversers.TraverserOrder:
==> X scala.meta.tests.transversers.TraverserOrder.traversal order is preserved  0.879s munit.FailException: /Users/tisue/scalameta/scalameta/testkit/src/test/scala/scala/meta/tests/transversers/TraverserOrder.scala:27 assertion failed
26:    }
27:    assert(errors.isEmpty)
28:  }
    at munit.FunSuite.assert(FunSuite.scala:11)
    at scala.meta.tests.transversers.TraverserOrder.$anonfun$new$1(TraverserOrder.scala:27)
```

in `.github/workflows/ci.yml` I see `"++2.13.4 testsJVM/test"` but apparently that doesn't include the testkit tests, hence CI didn't catch this

(but the Scala community build did!)

**Comment by tgodzik** [comment]
Thanks for reporting! I ignored the test for now in https://github.com/scalameta/scalameta/pull/2248

Traverser does not currently work with the new fields we added for Scala 3.
