### ISSUE TITLE
InvariantFailedException when attempting to extend a type

### ISSUE THREAD

**Issue by FlorianCassayre** [scalameta/scalameta#2741]
Version `4.5.4`:

```scala
trait B extends A.type
```
results in an `org.scalameta.invariants.InvariantFailedException`:
<details>

```
Exception in thread "main" org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable
found that scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable is false
where tpe = A.type
	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:19)
	at scala.meta.Init$.internal$265(Trees.scala:494)
	at scala.meta.Init$.apply(Trees.scala:493)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$initRest$1(ScalametaParser.scala:3834)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.initRest(ScalametaParser.scala:3812)
	at scala.meta.internal.parsers.ScalametaParser.initInsideTemplate(ScalametaParser.scala:3800)
	at scala.meta.internal.parsers.ScalametaParser.init(ScalametaParser.scala:3891)
	at scala.meta.internal.parsers.ScalametaParser.templateParents(ScalametaParser.scala:3901)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$template$1(ScalametaParser.scala:3949)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.template(ScalametaParser.scala:3937)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateOpt$1(ScalametaParser.scala:3980)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:3969)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$traitDef$1(ScalametaParser.scala:3617)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:339)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:341)
	at scala.meta.internal.parsers.ScalametaParser.traitDef(ScalametaParser.scala:3596)
	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3576)
	at scala.meta.internal.parsers.ScalametaParser.topLevelTmplDef(ScalametaParser.scala:3565)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4140)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4128)
	at scala.PartialFunction.$anonfun$runWith$1(PartialFunction.scala:231)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:230)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4121)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$14(ScalametaParser.scala:4337)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4337)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4292)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4285)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:296)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:337)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4285)
	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4290)
	at scala.meta.internal.parsers.ScalametaParser.parseSourceImpl(ScalametaParser.scala:132)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$1(ScalametaParser.scala:129)
	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:56)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:51)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:129)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
	at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:14)
	at a$.delayedEndpoint$a$1(a.scala:5)
	at a$delayedInit$body.apply(a.scala:1)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at a$.main(a.scala:1)
	at a.main(a.scala)
```

</details>

[Scastie](https://scastie.scala-lang.org/h0q06oYrRxiKE8mLdTNrCg)

**Comment by matthughes** [comment]
@tgodzik @p FWIW getting this error with latest (4.6.0) scalameta with this code:

```scala
  import natchez.*
  def dropTracing[F[_]: Applicative]: Kleisli[F, Span[F], *] ~> F = 
    new (Kleisli[F, Span[F], *] ~> F) {
      def apply[A](a: Kleisli[F, Span[F], A]): F[A] = a.run(emptySpan[F])
    }
```

**Comment by tgodzik** [comment]
Are you sure, I can't reproduce it in the test and nothing shows up when using Metals

**Comment by FlorianCassayre** [comment]
Also please note that there are likely many other places where an `InvariantFailedException` could be thrown, since this error essentially results from an internal assertion being violated.

**Comment by matthughes** [comment]
@tgodzik Here's a reproduction:

test.scala
```scala
//> using:
//>   scala "3.2.0"
//>   options "-Ykind-projector"

//> using lib "org.tpolecat::natchez-core:0.1.6"

import natchez.*
import cats.syntax.all.*
import cats.*
import cats.data.*

object Test {
  def dropTracing[F[_]: Applicative]: Kleisli[F, Span[F], *] ~> F =
    new (Kleisli[F, Span[F], *] ~> F) {
      def apply[A](a: Kleisli[F, Span[F], A]): F[A] = ???
    }
}
```

.scalafmt.conf
```
runner.dialect = scala3
version=3.6.0
```

Run `scala-cli fmt --scalafmt-config .scalafmt test.scala`. Pulling in 3.6.0 because that pulls in the latest scalameta:

```
scala-cli fmt --scalafmt-config .scalafmt test.scala
org.scalafmt.cli.FailedToFormat: /Users/MHughe008/work/vise/tmp/test.scala
Caused by: org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable
found that scala.meta.internal.trees.`package`.XtensionTreesType(tpe).isConstructable is false
where tpe = (Kleisli[F, Span[F], *] ~> F)
	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:19)
	at scala.meta.Init$.apply(Trees.scala:522)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$initRest$1(ScalametaParser.scala:3938)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.initRest(ScalametaParser.scala:3914)
	at scala.meta.internal.parsers.ScalametaParser.initInsideTemplate(ScalametaParser.scala:3897)
	at scala.meta.internal.parsers.ScalametaParser.init(ScalametaParser.scala:3995)
	at scala.meta.internal.parsers.ScalametaParser.templateParents(ScalametaParser.scala:4005)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$template$1(ScalametaParser.scala:4053)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.template(ScalametaParser.scala:4041)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr0$4(ScalametaParser.scala:2116)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$simpleExpr0$1(ScalametaParser.scala:2114)
	at scala.meta.internal.parsers.ScalametaParser.atPosTry(ScalametaParser.scala:354)
	at scala.meta.internal.parsers.ScalametaParser.autoPosTry(ScalametaParser.scala:364)
	at scala.meta.internal.parsers.ScalametaParser.simpleExpr0(ScalametaParser.scala:2085)
	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2083)
	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2067)
	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2049)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1616)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1505)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$3(ScalametaParser.scala:4349)
	at scala.meta.internal.parsers.ScalametaParser.stat(ScalametaParser.scala:4203)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$1(ScalametaParser.scala:4349)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$1$adapted(ScalametaParser.scala:4331)
	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:531)
	at scala.meta.internal.parsers.ScalametaParser.blockStatSeq(ScalametaParser.scala:4331)
	at scala.meta.internal.parsers.ScalametaParser.blockWithStats$1(ScalametaParser.scala:2377)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$block$1(ScalametaParser.scala:2382)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.block(ScalametaParser.scala:2376)
	at scala.meta.internal.parsers.ScalametaParser.blockExpr(ScalametaParser.scala:2373)
	at scala.meta.internal.parsers.ScalametaParser.exprMaybeIndented(ScalametaParser.scala:1411)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$funDefRest$1(ScalametaParser.scala:3599)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:359)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:361)
	at scala.meta.internal.parsers.ScalametaParser.funDefRest(ScalametaParser.scala:3561)
	at scala.meta.internal.parsers.ScalametaParser.funDefOrDclOrExtensionOrSecondaryCtor(ScalametaParser.scala:3503)
	at scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:3337)
	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:3316)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:4276)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$templateStat$1.applyOrElse(ScalametaParser.scala:4270)
	at scala.PartialFunction.$anonfun$runWith$1(PartialFunction.scala:231)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:230)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4222)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateStatSeq$1(ScalametaParser.scala:4262)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateStatSeq$1$adapted(ScalametaParser.scala:4261)
	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:531)
	at scala.meta.internal.parsers.ScalametaParser.templateStatSeq(ScalametaParser.scala:4261)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateBody$1(ScalametaParser.scala:4110)
	at scala.meta.internal.parsers.ScalametaParser.inBracesOr(ScalametaParser.scala:251)
	at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:247)
	at scala.meta.internal.parsers.ScalametaParser.templateBody(ScalametaParser.scala:4110)
	at scala.meta.internal.parsers.ScalametaParser.templateBodyOpt(ScalametaParser.scala:4118)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$templateOpt$1(ScalametaParser.scala:4099)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.templateOpt(ScalametaParser.scala:4073)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$objectDef$1(ScalametaParser.scala:3807)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:359)
	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:361)
	at scala.meta.internal.parsers.ScalametaParser.objectDef(ScalametaParser.scala:3799)
	at scala.meta.internal.parsers.ScalametaParser.tmplDef(ScalametaParser.scala:3676)
	at scala.meta.internal.parsers.ScalametaParser.topLevelTmplDef(ScalametaParser.scala:3657)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4241)
	at scala.meta.internal.parsers.ScalametaParser$$anonfun$4.applyOrElse(ScalametaParser.scala:4229)
	at scala.PartialFunction.$anonfun$runWith$1(PartialFunction.scala:231)
	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:230)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4222)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$14(ScalametaParser.scala:4437)
	at scala.Option.getOrElse(Option.scala:201)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4437)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4392)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4385)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:316)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:357)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4385)
	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4390)
	at scala.meta.internal.parsers.ScalametaParser.parseSourceImpl(ScalametaParser.scala:132)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$1(ScalametaParser.scala:129)
	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:56)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:51)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:129)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
	at org.scalafmt.config.ScalafmtParser$SourceParser$.apply(ScalafmtParser.scala:20)
	at org.scalafmt.config.ScalafmtRunner.parse(ScalafmtRunner.scala:67)
	at org.scalafmt.Scalafmt$.org$scalafmt$Scalafmt$$doFormatOne(Scalafmt.scala:143)
	at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:126)
	at org.scalafmt.Scalafmt$.formatCodeWithStyle(Scalafmt.scala:91)
	at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:78)
	at scala.util.Success.fold(Try.scala:281)
	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:78)
	at org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:69)
	at org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:53)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5(ScalafmtCoreRunner.scala:36)
	at org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$5$adapted(ScalafmtCoreRunner.scala:35)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:938)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:935)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$AWSTWrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$AWSFJTWrappedTask.compute(Tasks.scala:304)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)```

**Comment by tgodzik** [comment]
Ach, right! I missed that the exception is not showing up on the UI and only in Scala 3. Fixing it here https://github.com/scalameta/scalameta/pull/2918
