### ISSUE TITLE
crash in show[Semantics]

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#290]
```
    println(q"""
      object M {
        def main(args: Array[String]): Unit = {
          val x = 2 + 2
          val y = x * x
          println(y)
        }
      }
    """.show[Semantics])
```

leads to 

```
13:07 ~/Projects/core/sandbox1 (master)$ sr
java.lang.UnsupportedOperationException: implementation restriction: don't yet know how to typecheck Defn.Object
	at scala.meta.internal.hosts.scalac.contexts.Adapter.loop$1(Adapter.scala:118)
	at scala.meta.internal.hosts.scalac.contexts.Adapter.typecheck(Adapter.scala:123)
	at scala.meta.internal.prettyprinters.TreeSemantics$$anonfun$apply$1.apply(TreeSemantics.scala:12)
	at scala.meta.internal.prettyprinters.TreeSemantics$$anonfun$apply$1.apply(TreeSemantics.scala:11)
	at scala.meta.prettyprinters.Semantics$$anon$1.apply(Semantics.scala:10)
	at scala.meta.prettyprinters.Api$XtensionShow.show(Api.scala:10)
	at Test$.main(Test.scala:14)
	at Test.main(Test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by xeno-by** [comment]
Unblocks https://github.com/ValentinRutz/interpreter/issues/1
