### ISSUE TITLE
Error while using metals

### ISSUE THREAD

**Issue by phdoerfler** [scalameta/scalameta#3125]
Found this while using Metals in VS Code and neovim. Unfortunately, I don't remember precisely what I was doing in that moment but in the hope that this log might be useful, here goes:

```
2023.05.21 08:12:30 INFO  skipping build import with status 'Installed'[0m
May 21, 2023 8:13:04 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: jar%3Afile%3A%2F%2F%2FUsers%2Fphi%2FLibrary%2FCaches%2FCoursier%2Fv1%2Fhttps%2Frepo1.maven.org%2Fmaven2%2Forg%2Fscala-lang%2Fscala-library%2F2.12.17%2Fscala-library-2.12.17-sources.jar%21%2Fscala%2Fcollection%2Fgeneric%2FGenericCompanion.scala:20: error: ; expected but package found
package collection
^
jar%3Afile%3A%2F%2F%2FUsers%2Fphi%2FLibrary%2FCaches%2FCoursier%2Fv1%2Fhttps%2Frepo1.maven.org%2Fmaven2%2Forg%2Fscala-lang%2Fscala-library%2F2.12.17%2Fscala-library-2.12.17-sources.jar%21%2Fscala%2Fcollection%2Fgeneric%2FGenericCompanion.scala:20: error: ; expected but package found
package collection
^
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
	at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:387)
	at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:391)
	at scala.meta.internal.parsers.ScalametaParser.acceptStatSep(ScalametaParser.scala:407)
	at scala.meta.internal.parsers.ScalametaParser.acceptStatSepOpt(ScalametaParser.scala:411)
	at scala.meta.internal.parsers.ScalametaParser.statSeqBuf(ScalametaParser.scala:4299)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$13(ScalametaParser.scala:4524)
	at scala.Option.getOrElse(Option.scala:189)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:4524)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:320)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:366)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:4479)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:4472)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:320)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:366)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:4472)
	at scala.meta.internal.parsers.ScalametaParser.entrypointSource(ScalametaParser.scala:4477)
	at scala.meta.internal.parsers.ScalametaParser.parseSourceImpl(ScalametaParser.scala:127)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$1(ScalametaParser.scala:124)
	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:51)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:46)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:124)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:29)
	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
	at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:17)
	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:206)
	at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:54)

2023.05.21 08:13:19 INFO  Started: Metals version 0.11.12 in workspace '/Users/phi/Documents/workspace/Scala/spiht' for client Neovim 0.9.0.[0m
```

**Comment by tgodzik** [comment]
Thanks for reporting! Weirdly this seems to fail in https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/generic/GenericCompanion.scala
which should be perfectly fine.

**Comment by phdoerfler** [comment]
Strangely enough it complains about line 20 and mentions `;` and `package` but said line contains neither. In any case, I would be surprised if there was any reason to fail parsing code from scala-library. Very suspicious. What can I do to shine more light on this issue?

**Comment by phdoerfler** [comment]
I’m afraid no, I have not seen this issue again. I haven’t had time to work more on my little pet project ever since and that’s where I observed it. I also did not consciously use GenericCompanionHelper. I didn’t even know of that class until then 🤷
We might as well close this issue and re-open it if this error dares to surface again.

**Comment by tgodzik** [comment]
Let's close it then, we can reopen if anyone encounteres this again.
