### ISSUE TITLE
converter doesn't handle `apply` insertion

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#319]
The following exception:
```
[info]   scala.MatchError: immutable.this.List.apply[Int] (of class scala.meta.internal.ast.Term$ApplyType$Impl)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:73)
[info]   at scala.meta.internal.ast.mergeTrees$.apply(MergeTrees.scala:338)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:47)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:197)
[info]   at scala.meta.internal.ast.mergeTrees$.apply(MergeTrees.scala:338)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:47)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$$anonfun$apply$2.apply(MergeTrees.scala:330)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$$anonfun$apply$2.apply(MergeTrees.scala:330)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
```

rises when desugaring the expression:
```
      """{
      |val x = List apply (2)
      |}""".stripMargin.parse[Term]
```

**Comment by xeno-by** [comment]
This doesn't work because `List.apply` takes an implicit parameter, and that's not yet supported by the converter.
