### ISSUE TITLE
converter doesn't handle right-associative operators

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#321]
parsing :

```
"""{
        val x = List(2)
        3 :: x
}"""
```

gives exception:

```
[info]   scala.meta.internal.ast.MergeException: encountered unexpected trees during syntactic + semantic merge:
[info] Term.ApplyInfix(Lit(3), Term.Name("::"), Nil, Seq(Term.Name("x")))
[info] Term.Block(Seq(Defn.Val(Nil, Seq(Pat.Var.Term(Term.Name("x$1"))), Some(Type.Name("Int")), Lit(3)), Term.Apply(Term.ApplyType(Term.Select(Term.Name("x"), Term.Name("::")), Seq(Type.Name("Int"))), Seq(Term.Name("x$1")))))
[info] <-(Term.ApplyInfix) 3 :: x
[info] ->(Term.Block) {   val x$1: Int = 3   x.::[Int](x$1) }
[info] <-(Term.Block) {   val x = List(2)   3 :: x }
[info] ->(Term.Block) {   val x: List[Int] = immutable.this.List.apply[Int](2)   {...
[info]   at scala.meta.internal.ast.mergeTrees$.fail(MergeTrees.scala:403)
[info]   at scala.meta.internal.ast.mergeTrees$.scala$meta$internal$ast$mergeTrees$$failCorrelate(MergeTrees.scala:368)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:266)
[info]   at scala.meta.internal.ast.mergeTrees$.apply(MergeTrees.scala:338)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$.apply(MergeTrees.scala:47)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$$anonfun$apply$2.apply(MergeTrees.scala:330)
[info]   at scala.meta.internal.ast.mergeTrees$loop$2$$anonfun$apply$2.apply(MergeTrees.scala:330)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   ...
```

**Comment by xeno-by** [comment]
#148 is gone, and this issue is gone together with it.
