### ISSUE TITLE
annnotation parse error since 4.8.0

### ISSUE THREAD

**Issue by xuwei-k** [scalameta/scalameta#3257]
### scalameta version

NG: 4.8.0 to 4.8.5
OK: 4.7.8

### `build.sbt`

```scala
libraryDependencies += "org.scalameta" %% "scalameta" % "4.8.5"

scalaVersion := "2.13.11"
```

### `Main.scala`

```scala
import scala.meta._

object Main {
  def main(args: Array[String]): Unit = {
    val src = Input.String(
"""
@A(
  b =
    new B,
  c = d
)
def e = f
"""
)
    val p = implicitly[parsers.Parse[Stat]]

    println(p.apply(src, dialects.Scala3).get.structure)
  }
}
```

### result `sbt run`

```
[error] <input>:4: error: ; expected but , found
[error]     new B,
[error]          ^
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:16)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:22)
[error] 	at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:367)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expect(ScalametaParser.scala:369)
[error] 	at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:373)
[error] 	at scala.meta.internal.parsers.ScalametaParser.acceptStatSep(ScalametaParser.scala:389)
[error] 	at scala.meta.internal.parsers.ScalametaParser.iter$6(ScalametaParser.scala:4505)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$1(ScalametaParser.scala:4520)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$blockStatSeq$1$adapted(ScalametaParser.scala:4470)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:505
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockStatSeq(ScalametaParser.scala:4470)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockWithinDelims(ScalametaParser.scala:2436)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockWithStats$1(ScalametaParser.scala:2439)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$block$1(ScalametaParser.scala:2444)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:300)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:346)
[error] 	at scala.meta.internal.parsers.ScalametaParser.block(ScalametaParser.scala:2438)
[error] 	at scala.meta.internal.parsers.ScalametaParser.blockExpr(ScalametaParser.scala:2432)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr0(ScalametaParser.scala:2205)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2160)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2143)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:2028)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1609)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:303)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:347)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1514)
[error] 	at scala.meta.internal.parsers.ScalametaParser.iter$2(ScalametaParser.scala:1636)
[error] 	at scala.meta.internal.parsers.ScalametaParser.exprOtherRest(ScalametaParser.scala:1664)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$expr$2(ScalametaParser.scala:1610)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:303)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:347)
[error] 	at scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1514)
[error] 	at scala.meta.internal.parsers.ScalametaParser.argumentExpr(ScalametaParser.scala:2379)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$argumentExprsInParens$1(ScalametaParser.scala:2406)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$commaSeparated$1(ScalametaParser.scala:586)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$commaSeparated$1$adapted(ScalametaParser.scala:586)
[error] 	at scala.meta.internal.parsers.ScalametaParser.iter$1(ScalametaParser.scala:576)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$tokenSeparated$1(ScalametaParser.scala:582)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$tokenSeparated$1$adapted(ScalametaParser.scala:569)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:505
[error] 	at scala.meta.internal.parsers.ScalametaParser.tokenSeparated(ScalametaParser.scala:569)
[error] 	at scala.meta.internal.parsers.ScalametaParser.commaSeparatedWithIndex(ScalametaParser.scala:589)
[error] 	at scala.meta.internal.parsers.ScalametaParser.commaSeparated(ScalametaParser.scala:586)
[error] 	at scala.meta.internal.parsers.ScalametaParser.argumentExprsInParens(ScalametaParser.scala:2406)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$scala$meta$internal$parsers$ScalametaParser$$getArgClause$2(ScalametaParser.scala:2392)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$inParensAfterOpenOr(ScalametaParser.scala:238)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$inParensOnOpenOr(ScalametaParser.scala:229)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$scala$meta$internal$parsers$ScalametaParser$$getArgClause$1(ScalametaParser.scala:2393)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:300)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:346)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$getArgClause(ScalametaParser.scala:2382)
[error] 	at scala.meta.internal.parsers.ScalametaParser.body$5(ScalametaParser.scala:4055)
[error] 	at scala.meta.internal.parsers.ScalametaParser.maybeBody$1(ScalametaParser.scala:4072)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$initRest$3(ScalametaParser.scala:4075)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$initRest$3$adapted(ScalametaParser.scala:4053)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:505
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$initRest$1(ScalametaParser.scala:4053)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPosOpt(ScalametaParser.scala:303)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPosOpt(ScalametaParser.scala:347)
[error] 	at scala.meta.internal.parsers.ScalametaParser.initRest(ScalametaParser.scala:4038)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$annotsBuf$1(ScalametaParser.scala:3027)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoEndPos(ScalametaParser.scala:349)
[error] 	at scala.meta.internal.parsers.ScalametaParser.annotsBuf(ScalametaParser.scala:3027)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$nonLocalDefOrDcl$1(ScalametaParser.scala:3454)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$nonLocalDefOrDcl$1$adapted(ScalametaParser.scala:3453)
[error] 	at scala.meta.internal.parsers.ScalametaParser.scala$meta$internal$parsers$ScalametaParser$$listBy(ScalametaParser.scala:505
[error] 	at scala.meta.internal.parsers.ScalametaParser.nonLocalDefOrDcl(ScalametaParser.scala:3453)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4301)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$1.applyOrElse(ScalametaParser.scala:4296)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at scala.meta.internal.parsers.ScalametaParser.entrypointStat(ScalametaParser.scala:4333)
[error] 	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseStat$1(ScalametaParser.scala:61)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRuleAfterBOF(ScalametaParser.scala:51)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:46)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseStat(ScalametaParser.scala:61)
[error] 	at scala.meta.parsers.Parse$.$anonfun$parseStat$1(Parse.scala:14)
[error] 	at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:36)
[error] 	at Main$.main(Main.scala:17)
```

### run with scalameta 4.7.8

```
Defn.Def(List(Mod.Annot(Init(Type.Name("A"), Name(""), List(Term.ArgClause(List(Term.Assign(Term.Name("b"), Term.New(Init(Type.Name("B"), Name(""), Nil))), Term.Assign(Term.Name("c"), Term.Name("d"))), None))))), Term.Name("e"), Nil, None, Term.Name("f"))
```

### note

This is valid code in Scala 3

```
Welcome to Scala 3.3.1-RC4 (11.0.19, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                             
scala> class A(b: Any, c: Any) extends scala.annotation.StaticAnnotation
// defined class A
                                                                                                                                             
scala> class B
// defined class B
                                                                                                                                             
scala> val d, f = 3
val d: Int = 3
val f: Int = 3
                                                                                                                                             
scala> @A(
     |   b =
     |     new B,
     |   c = d
     | )
     | def e = f
def e: Int
```

similar issue 
- https://github.com/scalameta/scalameta/issues/3252

**Comment by kitbellew** [comment]
@xuwei-k thank you, do you have any other examples? my fix for #3252 was insufficient for this case, but perhaps you have a few more, so that i can fix it once and for all :)
