### ISSUE TITLE
Looking up some JDK symbols fails with JDK21

### ISSUE THREAD

**Issue by bjaglin** [scalameta/scalameta#3376]
Lookups that work with JDK20 do not work with JDK21:
```
scala.meta.internal.symtab.GlobalSymbolTable(scala.meta.Classpath(Nil), true).info("java/lang/System#lineSeparator().")
scala.meta.internal.symtab.GlobalSymbolTable(scala.meta.Classpath(Nil), true).info("java/nio/file/LinkOption#NOFOLLOW_LINKS.")
```

```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$this" is null
  at scala.collection.StringOps$.head$extension(StringOps.scala:1124)
  at scala.meta.internal.semanticdb.Scala$Names$.encode(Scala.scala:181)
  at scala.meta.internal.semanticdb.Scala$Descriptor.toString(Scala.scala:147)
  at scala.meta.internal.semanticdb.Scala$Descriptor.toString$(Scala.scala:140)
  at scala.meta.internal.semanticdb.Scala$Descriptor$Parameter.toString(Scala.scala:158)
  at scala.meta.internal.semanticdb.Scala$Symbols$.Global(Scala.scala:14)
  at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$13(Javacp.scala:175)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$9(Javacp.scala:169)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
  at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:135)
  at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$17(Javacp.scala:233)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
  at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:225)
  at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$17(Javacp.scala:233)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
  at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:225)
  at scala.meta.internal.javacp.Javacp$.parse(Javacp.scala:26)
  at scala.meta.internal.metacp.ClassfileInfos$.fromClassNode(ClassfileInfos.scala:55)
  at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:39)
  at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:70)
  ... 57 elided
```

Found through https://github.com/scalacenter/scalafix/pull/1810

**Comment by bjaglin** [comment]
[The current test suite does exhibit the problem](https://github.com/scalameta/scalameta/pull/3377)
```
scala.meta.tests.symtab.SymbolTableSuite:
  + _empty_/ 0.001s
  + _root_/ 0.0s
==> X scala.meta.tests.symtab.SymbolTableSuite.java/util/ArrayList#size.  0.006s java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$this" is null
    at scala.collection.StringOps$.head$extension(StringOps.scala:1124)
    at scala.meta.internal.semanticdb.Scala$Names$.encode(Scala.scala:181)
    at scala.meta.internal.semanticdb.Scala$Descriptor.toString(Scala.scala:147)
    at scala.meta.internal.semanticdb.Scala$Descriptor.toString$(Scala.scala:140)
    at scala.meta.internal.semanticdb.Scala$Descriptor$Parameter.toString(Scala.scala:158)
    at scala.meta.internal.semanticdb.Scala$Symbols$.Global(Scala.scala:14)
    at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$13(Javacp.scala:175)
    at scala.collection.immutable.List.map(List.scala:246)
    at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$9(Javacp.scala:169)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
    at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:135)
    at scala.meta.internal.javacp.Javacp$.$anonfun$sinfos$17(Javacp.scala:233)
    at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
    at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
    at scala.meta.internal.javacp.Javacp$.sinfos(Javacp.scala:225)
    at scala.meta.internal.javacp.Javacp$.parse(Javacp.scala:26)
    at scala.meta.internal.metacp.ClassfileInfos$.fromClassNode(ClassfileInfos.scala:55)
    at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:39)
    at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:70)
    at scala.meta.tests.symtab.SymbolTableSuite.$anonfun$check$1(SymbolTableSuite.scala:29)
```

**Comment by bjaglin** [comment]
With JDK<21, `method.node.parameters` is null for `java/util/ArrayList#ListItr#`<init>`().` and `java/nio/file/LinkOption#valueOf().`, while for JDK21, it's a non-empty list with null-name parameter(s), which [causes the failure as all methods get scanned to populate the symtab](https://github.com/scalameta/scalameta/blob/c46a391c11e34379c812b607c97671e5bc2a94f7/semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala#L171-L175).

`java/lang/System#Logger#Level#valueOf().` (JDK21 only) also has a non-empty `method.node.parameters` with a null-name parameter, so the 3 symbols seem to have the same failure mode.

```scala
import scala.meta.internal.metacp._
scala.meta.internal.classpath.ClasspathIndex(scala.meta.Classpath(Nil), true).getClassfile("java/util/ArrayList$ListItr.class").get.toClassNode.methods.get(0).parameters
```

From there, I am not sure what to do...

**Comment by SethTisue** [comment]
seems reminiscent of https://github.com/scala/bug/issues/12783
