### ISSUE TITLE
"invalid unicode surrogate pair"

### ISSUE THREAD

**Issue by keynmol** [scalameta/scalameta#3402]
Reproduction:

```scala
//> using dep org.scalameta:scalameta_2.13:4.8.14

import scala.meta.*

val file = """
object Hello {
  final val MIN_HIGH_SURROGATE: Char = '\uD800'
}
"""

@main def hello = 
  println(file.parse[Source].get)
```

Whereas the file compiles fine under 2.13 and 3: https://scastie.scala-lang.org/QX3y9ZX6TiyNEqjdFImGyQ

```
Exception in thread "main" <input>:3: error: invalid unicode surrogate pair
  final val MIN_HIGH_SURROGATE: Char = '\uD800'
                                        ^
        at scala.meta.internal.tokenizers.Reporter.readerError(Reporter.scala:20)
        at scala.meta.internal.tokenizers.Reporter.readerError$(Reporter.scala:20)
        at scala.meta.internal.tokenizers.Reporter$$anon$1.readerError(Reporter.scala:33)
        at scala.meta.internal.tokenizers.Reporter.readerError(Reporter.scala:22)
        at scala.meta.internal.tokenizers.Reporter.readerError$(Reporter.scala:22)
        at scala.meta.internal.tokenizers.Reporter$$anon$1.readerError(Reporter.scala:33)
        at scala.meta.internal.tokenizers.CharArrayReader.nextRawChar(CharArrayReader.scala:70)
        at scala.meta.internal.tokenizers.LegacyScanner.fetchSingleQuote$1(LegacyScanner.scala:379)
        at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:412)
        at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:211)
        at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1011)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:24)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.$anonfun$tokenize$1(ScalametaTokenizer.scala:17)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:962)
        at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:17)
        at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:332)
        at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:25)
        at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:14)
        at scala.meta.internal.parsers.ScannerTokens$.apply(ScannerTokens.scala:914)
        at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:33)
        at scala.meta.parsers.Parse$$anon$1.apply(Parse.scala:35)
        at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:25)
        at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:14)
```

Originally I spotted this issue when Metals was loading Scala Native's standard javalib and crashing there: https://github.com/scala-native/scala-native/blob/main/javalib/src/main/scala/java/lang/Character.scala#L215

And now because of a globally enabled semanticdb plugin I think I have issues with SN's build itself..

**Comment by tgodzik** [comment]
@kitbellew any idea why it's an error currently, wouldn't it make sense to just not see it as a pair? I did a workaround in Metals, would it make sense to have in scalameta too?

https://github.com/scalameta/metals/commit/43d8f8e6b87a09dd32984a74df56d56f5ac41a08#diff-3a3a3830b0706b86251dbf56ee4d291a217462c614cf4bc1ecf4d04292140e9b
