### ISSUE TITLE
InvariantFailed on new Pat.Arg.SeqWildcard() syntax

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#501]
``` scala
// OK
> """      case List(_: BlockExpr, _: MatchExpr, _*)   ⇒ false""".parse[Case].get.structure
res2: String = """
Case(Pat.Extract(Term.Name("List"), Nil, Seq(Pat.Typed(Pat.Wildcard(), Type.Name("BlockExpr")), Pat.Typed(Pat.Wildcard(), Type.Name("MatchExpr")), Pat.Arg.SeqWildcard())), None, Lit(false))
"""

// but syntax is not supported in Dotty
rror: The syntax `_*' is no longer supported; use `x : _*' instead
      case List(_: BlockExpr, _: MatchExpr, _*)   ⇒ false
                                            ^
// So I refactor using the new syntax
> """      case List(_: BlockExpr, _: MatchExpr, x:_*)   ⇒ false""".parse[Case].get.structure
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying bounds.lo.nonEmpty.||(bounds.hi.nonEmpty)
found that bounds.lo.nonEmpty is false
and also bounds.hi.nonEmpty is false
where bounds =
  org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
  scala.meta.Pat$Type$Placeholder$.internal$164(Trees.scala:285)
  scala.meta.Pat$Type$Placeholder$.apply(Trees.scala:284)
  scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive$$anonfun$loop$2$11.apply(ScalametaParser.scala:1124)
  scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive$$anonfun$loop$2$11.apply(ScalametaParser.scala:1124)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive$class.loop$2(ScalametaParser.scala:1124)
  scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive$class.patternTyp(ScalametaParser.scala:1141)
  scala.meta.internal.parsers.ScalametaParser$seqOK$.patternTyp(ScalametaParser.scala:2483)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern1$1.apply(ScalametaParser.scala:2298)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern1$1.apply(ScalametaParser.scala:2284)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern1(ScalametaParser.scala:2284)
  scala.meta.internal.parsers.ScalametaParser$seqOK$.pattern1(ScalametaParser.scala:2483)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern(ScalametaParser.scala:2241)
  scala.meta.internal.parsers.ScalametaParser$seqOK$.pattern(ScalametaParser.scala:2483)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$patterns$1.apply(ScalametaParser.scala:2230)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$patterns$1.apply(ScalametaParser.scala:2230)
  scala.meta.internal.parsers.ScalametaParser.partOrEllipsis$1(ScalametaParser.scala:767)
  scala.meta.internal.parsers.ScalametaParser.tokenSeparated(ScalametaParser.scala:773)
  scala.meta.internal.parsers.ScalametaParser.commaSeparated(ScalametaParser.scala:779)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.patterns(ScalametaParser.scala:2230)
  scala.meta.internal.parsers.ScalametaParser$seqOK$.patterns(ScalametaParser.scala:2483)
  scala.meta.internal.parsers.ScalametaParser.seqPatterns(ScalametaParser.scala:2510)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$argumentPatterns$1.apply(ScalametaParser.scala:2515)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$argumentPatterns$1.apply(ScalametaParser.scala:2514)
  scala.meta.internal.parsers.ScalametaParser.inParens(ScalametaParser.scala:325)
  scala.meta.internal.parsers.ScalametaParser.argumentPatterns(ScalametaParser.scala:2513)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$simplePattern$2.apply(ScalametaParser.scala:2450)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$simplePattern$2.apply(ScalametaParser.scala:2424)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.simplePattern(ScalametaParser.scala:2424)
  scala.meta.internal.parsers.ScalametaParser$noSeq$.simplePattern(ScalametaParser.scala:2487)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern3(ScalametaParser.scala:2350)
  scala.meta.internal.parsers.ScalametaParser$noSeq$.pattern3(ScalametaParser.scala:2487)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern2$1.apply(ScalametaParser.scala:2319)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern2$1.apply(ScalametaParser.scala:2318)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern2(ScalametaParser.scala:2318)
  scala.meta.internal.parsers.ScalametaParser$noSeq$.pattern2(ScalametaParser.scala:2487)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern1$1.apply(ScalametaParser.scala:2285)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$pattern1$1.apply(ScalametaParser.scala:2284)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern1(ScalametaParser.scala:2284)
  scala.meta.internal.parsers.ScalametaParser$noSeq$.pattern1(ScalametaParser.scala:2487)
  scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.pattern(ScalametaParser.scala:2241)
  scala.meta.internal.parsers.ScalametaParser$noSeq$.pattern(ScalametaParser.scala:2487)
  scala.meta.internal.parsers.ScalametaParser.pattern(ScalametaParser.scala:2505)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$caseClause$1.apply(ScalametaParser.scala:2100)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$caseClause$1.apply(ScalametaParser.scala:2098)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.caseClause(ScalametaParser.scala:2098)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$parseCase$1.apply(ScalametaParser.scala:113)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$parseCase$1.apply(ScalametaParser.scala:113)
  scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:46)
  scala.meta.internal.parsers.ScalametaParser.parseCase(ScalametaParser.scala:113)
  scala.meta.parsers.Parse$$anonfun$parseCase$1.apply(Parse.scala:24)
  scala.meta.parsers.Parse$$anonfun$parseCase$1.apply(Parse.scala:24)
  scala.meta.internal.parsers.ScalametaParser$$anon$201.apply(ScalametaParser.scala:3651)
  scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
  scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
  $sess.cmd3$.<init>(cmd3.sc:1)
  $sess.cmd3$.<clinit>(cmd3.sc:-1)

```

**Comment by olafurpg** [comment]
This one is popping up quite a bit while building the community build with scalahost.
```
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying tempClass.!=(null).&&(scala.reflect.`package`.classTag[scala.meta.Pat](((ClassTag.apply[scala.meta.Pat](classOf[scala.meta.Pat])): scala.ref
lect.ClassTag[scala.meta.Pat])).unapply(temp).isDefined)
found that scala.reflect.`package`.classTag[scala.meta.Pat](((ClassTag.apply[scala.meta.Pat](classOf[scala.meta.Pat])): scala.reflect.ClassTag[scala.meta.P
at])).unapply(temp).isDefined is false
where temp = _*
where tempClass = class scala.meta.Pat$Arg$SeqWildcard$PatArgSeqWildcardImpl
        at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
        at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$unquoteXmlPattern$1.apply(ScalametaParser.scala:2350)
        at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$unquoteXmlPattern$1.apply(ScalametaParser.scala:2350)
        at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:345)
        at scala.meta.internal.parsers.ScalametaParser.dropAnyBraces(ScalametaParser.scala:356)
        at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.unquoteXmlPattern(ScalametaParser.scala:2350)
        at scala.meta.internal.parsers.ScalametaParser$xmlSeqOK$.unquoteXmlPattern(ScalametaParser.scala:2573)
        at scala.meta.internal.parsers.ScalametaParser.unquoteXmlPattern(ScalametaParser.scala:2590)
        at scala.meta.internal.parsers.ScalametaParser$$anonfun$xmlPat$1.apply(ScalametaParser.scala:1514)
        at scala.meta.internal.parsers.ScalametaParser$$anonfun$xmlPat$1.apply(ScalametaParser.scala:1514)
        at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.loop$3(ScalametaParser.scala:1489)
        at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.apply(ScalametaParser.scala:1499)
        at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.apply(ScalametaParser.scala:1463)
        at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
        at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:413)
        at scala.meta.internal.parsers.ScalametaParser.interpolate(ScalametaParser.scala:1463)
        at scala.meta.internal.parsers.ScalametaParser.xmlPat(ScalametaParser.scala:1514)
```

**Comment by xeno-by** [comment]
@olafurpg Could you provide a reproduction?

**Comment by olafurpg** [comment]
It would be a lot easier to find a minimal repro if scalahost-nsc catched errors and printed out the stacktrace with the culprit filename. Currently the stacktrace does not contain the source file where the error happened.

**Comment by xeno-by** [comment]
At the head of https://github.com/scalameta/scalameta/pull/854, we: 1) no longer crash compilation if semanticdb crashes, 2) instead, we emit a compiler error that features `unit.source.file.path` (can be relative, can be absolute - depending on what was passed in arguments to the scalac invocation) and the original exception.

**Comment by xeno-by** [comment]
Your recently reported exception seems to be something different from the original exception. Could you try to rerun the community build with a new build of meta and submit the new exception together with a reproduction in a separate issue?
