### ISSUE TITLE
crasher with certain sources

### ISSUE THREAD

**Issue by paulp** [scalameta/scalameta#525]
Edit: somehow I thought it was the trailing newline, but it isn't. However it's definitely [that source](https://github.com/m50d/paperdoll/blob/master/scalaz/src/main/scala/paperdoll/scalaz/StateLayer.scala).

```
scala> parse("m50d/paperdoll/scalaz/src/main/scala/paperdoll/scalaz/StateLayer.scala") collect { case x: Name => x }
parsing(/s/github/m50d/paperdoll/scalaz/src/main/scala/paperdoll/scalaz/StateLayer.scala)
java.lang.IllegalArgumentException: [2353..2352) is not a valid range
  at scala.meta.inputs.Position$Range.<init>(Position.scala:26)
  at scala.meta.inputs.Position$Range$.apply(Position.scala:35)
  at scala.meta.internal.ast.InternalTree$class.pos(InternalTrees.scala:73)
  at scala.meta.Name$Anonymous$NameAnonymousImpl.pos(Trees.scala:41)
  at scala.meta.internal.prettyprinters.TreeSyntax$$anonfun$apply$37.apply(TreeSyntax.scala:555)
```

**Comment by paulp** [comment]
If I wrap the Name toString in a Try we see...
```
Success(A)
Success(S)
Success(A)
Success(StateHandler)
Success(initialState)
Failure(java.lang.IllegalArgumentException: [2353..2352) is not a valid range)
Success(translateState)
Success(F)
Success(_)
Success(S)
Success(ms)
Success(MonadState)
Success(F)
```

**Comment by paulp** [comment]
So I think it's actually related to EOL conventions. That file has old school `\r\n` going on. Comparing string literals which parse to file slurped data which throws that exception, line endings are the only difference I detect.

**Comment by xeno-by** [comment]
Just checked now, and the file parses successfully with scala.meta 1.6.0.
