### ISSUE TITLE
invalid format

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#664]
```scala
java.lang.RuntimeException: 15:invalid format: _root_.scala.collection.mutable.ListBuffer.;_root_.scala.collection.mutable.ListBuffer#
[134..144): ListBuffer => _root_.scala.collection.mutable.ListBuffer.;_root_.scala.collection.mutable.ListBuffer#
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.semantic.v1.Database$.readSection$1(Database.scala:83)
	at scala.meta.semantic.v1.Database$.apply(Database.scala:91)
	at scala.meta.semantic.v1.Database$.apply(Database.scala:105)
	at scala.meta.internal.scalahost.ScalahostPipeline$ScalahostComponent$ScalahostPhase.run(ScalahostPipeline.scala:30)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
```
when  compiling Slick with the scalahost compiler plugin.

**Comment by olafurpg** [comment]
After some debugging, I suspect this issue is caused by the fact that sbt builds multi-project builds in parallel and scalahost tried to read an incomplete database that was being serialized. I am not able to reproduce if I run compile each project individually.

**Comment by olafurpg** [comment]
Here is another related error

```scala
java.lang.RuntimeException: 9192:invalid symbol format
Boolean)" is lazy` => _root_.scalaprops.PropertyTest.`"forAll(result: => Boolean)" is lazy`.
                                                                                            ^
[67..105): `"forAll(result: => Boolean)" is lazy` => _root_.scalaprops.PropertyTest.`"forAll(result: => Boolean)" is lazy`.
        at scala.sys.package$.error(package.scala:27)
        at scala.meta.semantic.v1.Database$.readSection$1(Database.scala:83)
        at scala.meta.semantic.v1.Database$.apply(Database.scala:92)
        at scala.meta.semantic.v1.Database$.apply(Database.scala:106)
        at scala.meta.internal.scalahost.ScalahostPipeline$ScalahostComponent$ScalahostPhase.run(ScalahostPipeline.scala:30)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
```

**Comment by xeno-by** [comment]
@olafurpg Can we close this issue then?

**Comment by xeno-by** [comment]
Also, speaking of reading an incomplete database, fixing #650 and #666 should completely prevent that issue.

**Comment by olafurpg** [comment]
Yes, we can close this. I have a WIP PR that makes it possible to configure the persistence scheme.
