### ISSUE TITLE
unsupported file <no file>

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#665]
While compiling scalactic with scalahost 

```scala
java.lang.RuntimeException: unsupported file <no file>
        at scala.sys.package$.error(package.scala:27)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGFileAddr.toAddr(LocationOps.scala:22)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGSourceFileAddr.toAddr(LocationOps.scala:16)
        at scala.meta.internal.scalahost.v1.online.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:28)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.scala$meta$internal$scalahost$v1$online$DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$traverser$$success$1(DatabaseOps.scala:139)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.tryMend$1(DatabaseOps.scala:167)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.tryFindMtree(DatabaseOps.scala:219)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:271)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:133)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1294)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:273)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:133)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1283)
[error] (scalacticMacro/compile:compileIncremental) unsupported file <no file>
```

**Comment by olafurpg** [comment]
Here is another related error

```scala
java.lang.RuntimeException: unsupported file <console>
        at scala.sys.package$.error(package.scala:27)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGFileAddr.toAddr(LocationOps.scala:22)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGSourceFileAddr.toAddr(LocationOps.scala:16)
        at scala.meta.internal.scalahost.v1.online.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:28)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.success$1(DatabaseOps.scala:139)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.tryMpos$1(DatabaseOps.scala:174)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.tryFindMtree(DatabaseOps.scala:194)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.traverse(DatabaseOps.scala:271)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.traverse(DatabaseOps.scala:264)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$traverser$4$.traverse(DatabaseOps.scala:133)
        at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2484)
        at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
```

**Comment by olafurpg** [comment]
Closing, since I am unable to reproduce this error with scalahost. I suspect the error is caused by how scalafix manually mixes the scalahost plugin in https://github.com/scalacenter/scalafix/pull/57

I am leaning towards dropping the scalafix compiler plugin in favor of using only the scala.meta Mirror for semantic analysis. This would also require us to upstream some features from ScalafixMirror, benefiting all scala.meta users.

**Comment by olafurpg** [comment]
Reopening since I was able to reproduce this error with running scalahost-sbt on minitest from the community build,

```scala
[info] Resolving com.lihaoyi#sourcecode_2.11;0.1.3 ...java.lang.RuntimeException: unsupported file <no file>
        at scala.sys.package$.error(package.scala:27)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGFileAddr.toAddr(LocationOps.scala:22)
        at scala.meta.internal.scalahost.v1.LocationOps$XtensionGSourceFileAddr.toAddr(LocationOps.scala:16)
        at scala.meta.internal.scalahost.v1.online.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:28)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.scala$meta$internal$scalaho
st$v1$online$DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$traverser$$success$1(DatabaseOps.scala:139)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.tryMend$1(DatabaseOps.scala
:167)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.tryFindMtree(DatabaseOps.sc
ala:219)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:
271)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:
133)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1294)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:
273)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:
133)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1283)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatabase$$anonfun$toDatabase$1$traverser$4$.traverse(DatabaseOps.scala:
273)
        at scala.meta.internal.scalahost.v1.online.DatabaseOps$XtensionCompilationUnitDatab
```

**Comment by olafurpg** [comment]
I am still able to reproduce this error in the community build with the latest scalahost

```
java.lang.RuntimeException: unsupported file <no file>
        at scala.sys.package$.error(package.scala:27)
        at scala.meta.internal.semantic.InputOps$XtensionGSourceFileInput.toAbsolutePath(InputOps.scala:13)
        at scala.meta.internal.semantic.InputOps$XtensionGPositionMPosition.toMeta(InputOps.scala:20)
        at scala.meta.internal.semantic.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:25)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.scala$meta$internal$semantic$A
ttributesOps$XtensionCompilationUnitAttributes$$anonfun$traverser$$success$1(AttributesOps.scala:141)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.tryMstart$1(AttributesOps.scal
a:171)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.tryFindMtree(AttributesOps.sca
la:237)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:3
22)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:1
36)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1283)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:3
24)
        at scala.meta.internal.semantic.AttributesOps$XtensionCompilationUnitAttributes$$anonfun$toAttributes$1$traverser$4$.traverse(AttributesOps.scala:1
36)
        at scala.reflect.internal.Trees$class.traverseComponents$1(Trees.scala:1294)
        at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1330)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
```

**Comment by xeno-by** [comment]
This should be very easy to fix by adding something like `if (!unit.source.file.name.endsWith(".scala")) return` to https://github.com/scalameta/scalameta/blob/78338480f560fb7948ee14ae0079651d1bf551c7/scalahost/nsc/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala#L44.

**Comment by olafurpg** [comment]
That sounds like a reasonable solution, I opened a PR using that approach https://github.com/scalameta/scalameta/pull/857

**Comment by olafurpg** [comment]
I am still seeing this error in the logs while compiling the CB: 

```scala
error] failed to generate semanticdb for /home/geirsson/megarepos/framework/core/json-scalaz7/src/test/scala/net/liftweb/json/scalaz/ValidationExample.sca
la:
[error] java.lang.RuntimeException: unsupported file <no file>
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at scala.meta.internal.semantic.InputOps$XtensionGSourceFileInput$$anonfun$toInput$1.apply(InputOps.scala:19)
[error]         at scala.meta.internal.semantic.InputOps$XtensionGSourceFileInput$$anonfun$toInput$1.apply(InputOps.scala:16)
[error]         at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
[error]         at scala.meta.internal.semantic.InputOps$XtensionGSourceFileInput.toInput(InputOps.scala:16)
[error]         at scala.meta.internal.semantic.InputOps$XtensionGPositionMPosition.toMeta(InputOps.scala:39)
[error]         at scala.meta.internal.semantic.SymbolOps$XtensionGSymbolMSymbol.toSemantic(SymbolOps.scala:26)
```

Seems we can return Symbol/Position.None there instead of throwing exception.
