### ISSUE TITLE
OfflineMirror should not crash when sourcepath contains non .scala files

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#814]
If sourcepath contains a file like GetResult.fm that is not valid scala code then it crashes like this
```
/Users/ollie/dev/scalafix/target/it/slick/slick/src/main/scala/slick/jdbc/GetResult.fm:46: error: identifier expected but double constant found
<#list 2..22 as i>
         ^
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:18)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:18)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
	at scala.m
...
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:42)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:153)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:31)
	at scala.meta.internal.parsers.ScalametaParser$$anon$202.apply(ScalametaParser.scala:3788)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
	at scala.meta.internal.scalahost.v1.offline.Mirror.$anonfun$sources$2(Mirror.scala:42)
	at scala.collection.immutable.List.map(List.scala:287)
```

**Comment by xeno-by** [comment]
Fixed via #808.
