### ISSUE TITLE
Unsupported quoting position

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#843]
```scala
@ t"af.${Type.Name("a")}"
cmd12.sc:1: exception during macro expansion:
java.lang.UnsupportedOperationException: unsupported unquoting position
	at scala.meta.Term$Name$Quasi$TermNameQuasiImpl.value(Trees.scala:54)
	at scala.meta.Term$Name$Quasi$TermNameQuasiImpl.value(Trees.scala:54)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$convertToTypeId$2(ScalametaParser.scala:811)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:401)
	at scala.meta.internal.parsers.ScalametaParser.convertToTypeId(ScalametaParser.scala:811)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$simpleType$1(ScalametaParser.scala:1115)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:401)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:407)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.simpleType(ScalametaParser.scala:1106)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.simpleType$(ScalametaParser.scala:1105)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.simpleType(ScalametaParser.scala:2556)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.annotType(ScalametaParser.scala:1088)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.annotType$(ScalametaParser.scala:1088)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.annotType(ScalametaParser.scala:2556)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.compoundType(ScalametaParser.scala:1061)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.compoundType$(ScalametaParser.scala:1057)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.compoundType(ScalametaParser.scala:2556)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.infixType(ScalametaParser.scala:1016)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.infixType$(ScalametaParser.scala:1015)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.infixType(ScalametaParser.scala:2556)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.$anonfun$typ$1(ScalametaParser.scala:996)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:401)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:407)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ(ScalametaParser.scala:993)
	at scala.meta.internal.parsers.ScalametaParser$PatternContextSensitive.typ$(ScalametaParser.scala:993)
	at scala.meta.internal.parsers.ScalametaParser$outPattern$.typ(ScalametaParser.scala:2556)
	at scala.meta.internal.parsers.ScalametaParser.typ(ScalametaParser.scala:2576)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseType$1(ScalametaParser.scala:99)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:42)
	at scala.meta.internal.parsers.ScalametaParser.parseType(ScalametaParser.scala:99)
	at scala.meta.parsers.Parse$.$anonfun$parseType$1(Parse.scala:18)
```

I expected to get the tree `Type.Select(Term.Name("af"), Type.Name("a"))`

**Comment by xeno-by** [comment]
This is a pretty outrageous bug. No idea how it could remain hidden all this time.
