### ISSUE TITLE
Crash while parsing _* in xml literal in pattern position

### ISSUE THREAD

**Issue by allanrenucci** [scalameta/scalameta#870]
```scala
"e match { case <a>{_*}</a> => }".parse[Stat]
```
```
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying tempClass.!=(null).&&(scala.reflect.`package`.classTag[scala.meta.Pat](((ClassTag.apply[scala.meta.Pat](classOf[scala.meta.Pat])): scala.reflect.ClassTag[scala.meta.Pat])).unapply(temp).isDefined)
found that scala.reflect.`package`.classTag[scala.meta.Pat](((ClassTag.apply[scala.meta.Pat](classOf[scala.meta.Pat])): scala.reflect.ClassTag[scala.meta.Pat])).unapply(temp).isDefined is false
where temp = _*
where tempClass = class scala.meta.Pat$Arg$SeqWildcard$PatArgSeqWildcardImpl
  at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
  at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$unquoteXmlPattern$1.apply(ScalametaParser.scala:2350)
  at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$$anonfun$unquoteXmlPattern$1.apply(ScalametaParser.scala:2350)
  at scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:345)
  at scala.meta.internal.parsers.ScalametaParser.dropAnyBraces(ScalametaParser.scala:356)
  at scala.meta.internal.parsers.ScalametaParser$SeqContextSensitive$class.unquoteXmlPattern(ScalametaParser.scala:2350)
  at scala.meta.internal.parsers.ScalametaParser$xmlSeqOK$.unquoteXmlPattern(ScalametaParser.scala:2575)
  at scala.meta.internal.parsers.ScalametaParser.unquoteXmlPattern(ScalametaParser.scala:2592)
  at scala.meta.internal.parsers.ScalametaParser$$anonfun$xmlPat$1.apply(ScalametaParser.scala:1514)
  at scala.meta.internal.parsers.ScalametaParser$$anonfun$xmlPat$1.apply(ScalametaParser.scala:1514)
  at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.loop$3(ScalametaParser.scala:1489)
  at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.apply(ScalametaParser.scala:1499)
  at scala.meta.internal.parsers.ScalametaParser$$anonfun$interpolate$1.apply(ScalametaParser.scala:1463)
  at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
  at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:413)
  at scala.meta.internal.parsers.ScalametaParser.interpolate(ScalametaParser.scala:1463)
  at scala.meta.internal.parsers.ScalametaParser.xmlPat(ScalametaParser.scala:1514)
...
```

**Comment by allanrenucci** [comment]
This parses though
```scala
 "e match { case <a>{ns @ _*}</a> => }".parse[Stat]
```

**Comment by allanrenucci** [comment]
I'd like to give a shot at fixing this.
The issue is that the parser parses a `Pat.Arg.SeqWildcard` but expects a `Pat`.
@xeno-by What is the reason for `Pat` to extends `Pat.Arg` and not the other way around? (i.e. `Pat.Arg <: Pat`)

**Comment by xeno-by** [comment]
@allanrenucci This is one of the suboptimal parts of our design. Incidentally, I took care of it very recently in the 2.x branch. Feel free to do whatever hack you find necessary to support this in 1.x.
