### ISSUE TITLE
ScalaDoc generation raises NullPointerException when @typeclass annotation is used

### ISSUE THREAD

**Issue by swachter** [scalameta/scalameta#909]
When the @typeclass annotation of the [Simulacrum](https://github.com/mpilquist/simulacrum) project is used then the project can be compiled but scaladoc generation raises a NullPointerException.

A small sample project can be found [here](https://github.com/swachter/macro-scaladoc). Parts of the project follow for convenience:

From build.sbt:

```
scalaVersion := "2.12.2"

libraryDependencies ++= Seq(
  "com.github.mpilquist" %% "simulacrum" % "0.10.0",
  "org.scalameta" %% "scalameta" % "1.8.0"
)

addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M9" cross CrossVersion.full)

scalacOptions += "-Xplugin-require:macroparadise"
```

TestTypeClass.scala:

```scala
@typeclass
trait TestTypeClass[T]

object TestTypeClass {
  implicit val string = new TestTypeClass[String] {}
}
```

Main.scala:

```scala
object Main {

  val tc = TestTypeClass[String]
}
```

The NPE:

```
java.lang.NullPointerException
	at scala.tools.nsc.typechecker.Typers$Typer.callToCompanionConstr(Typers.scala:3276)
	at scala.tools.nsc.typechecker.Typers$Typer.tryNamesDefaults$1(Typers.scala:3540)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3563)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4717)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4745)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5510)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5527)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedAnnotation(Typers.scala:3835)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$annotSig$4(Namers.scala:1767)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$annotSig$3(Namers.scala:1767)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo$lzycompute(AnnotationInfos.scala:212)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo(AnnotationInfos.scala:212)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.atp(AnnotationInfos.scala:214)
	at scala.reflect.internal.AnnotationInfos$AnnotationInfo.symbol(AnnotationInfos.scala:286)
	at scala.reflect.internal.AnnotationInfos$AnnotationInfo.matches(AnnotationInfos.scala:307)
	at scala.reflect.internal.AnnotationInfos$Annotatable.dropOtherAnnotations(AnnotationInfos.scala:60)
	at scala.reflect.internal.AnnotationInfos$Annotatable.hasAnnotation(AnnotationInfos.scala:45)
	at scala.reflect.internal.AnnotationInfos$Annotatable.hasAnnotation$(AnnotationInfos.scala:43)
	at scala.reflect.internal.Symbols$Symbol.hasAnnotation(Symbols.scala:206)
	at scala.reflect.internal.Symbols$Symbol.hasDeprecatedInheritanceAnnotation(Symbols.scala:901)
	at scala.tools.nsc.typechecker.Typers$Typer.validateParentClass$1(Typers.scala:1746)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$validateParentClasses$8(Typers.scala:1775)
	at scala.tools.nsc.typechecker.Typers$Typer.validateParentClasses(Typers.scala:1775)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1962)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1811)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5476)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2456)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5485)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:491)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:491)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5520)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5527)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5635)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1069)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1615)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1784)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1749)
	at scala.tools.nsc.typechecker.Namers$Namer$AccessorTypeCompleter.completeImpl(Namers.scala:927)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1946)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1944)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1939)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1521)
	at scala.reflect.internal.Symbols$Symbol.tpeHK(Symbols.scala:1456)
	at scala.reflect.internal.Types$Type.memberType(Types.scala:704)
	at scala.tools.nsc.typechecker.Implicits$ImplicitInfo.tpe(Implicits.scala:214)
	at scala.tools.nsc.typechecker.Implicits$ImplicitInfo.computeIsCyclicOrErroneous(Implicits.scala:224)
	at scala.tools.nsc.typechecker.Implicits$ImplicitInfo.isCyclicOrErroneous(Implicits.scala:219)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.isIneligible(Implicits.scala:831)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.survives(Implicits.scala:839)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.$anonfun$eligible$2(Implicits.scala:896)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.$anonfun$eligible$2$adapted(Implicits.scala:896)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.$anonfun$eligible$1(Implicits.scala:896)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.<init>(Implicits.scala:895)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1010)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1396)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:81)
	at scala.tools.nsc.doc.ScaladocGlobal$$anon$1.inferImplicit(ScaladocGlobal.scala:50)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView(Implicits.scala:43)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView$(Implicits.scala:42)
	at scala.tools.nsc.doc.ScaladocGlobal$$anon$1.inferImplicitView(ScaladocGlobal.scala:50)
	at scala.tools.nsc.typechecker.Typers$Typer.inferView(Typers.scala:233)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMember(Typers.scala:1275)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToName(Typers.scala:1339)
	at scala.tools.nsc.typechecker.Typers$Typer.applyMeth$1(Typers.scala:1134)
	at scala.tools.nsc.typechecker.Typers$Typer.hasPolymorphicApply$1(Typers.scala:1135)
	at scala.tools.nsc.typechecker.Typers$Typer.applyPossible$1(Typers.scala:1140)
	at scala.tools.nsc.typechecker.Typers$Typer.shouldInsertApply$1(Typers.scala:1148)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1157)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1214)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5577)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5638)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeApply$1(Typers.scala:5289)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5487)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5520)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5527)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5635)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5723)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1069)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1615)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1784)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1749)
	at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:905)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1946)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1944)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1939)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1521)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1669)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5169)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1858)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5477)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5176)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5479)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5620)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:423)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:416)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1501)
	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:44)
	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:124)
	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:131)
	at xsbt.Runner.run(ScaladocInterface.scala:26)
	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:73)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:68)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:64)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:56)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:49)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:47)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:84)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:79)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:54)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:39)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:829)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:807)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by xeno-by** [comment]
What happens if you remove the library dependency on scalameta? Just trying to figure out what could cause the crash.

**Comment by swachter** [comment]
The same NPE is raised.

**Comment by xeno-by** [comment]
I think that it's the paradise plugin that is at fault. I resubmitted this issue at https://github.com/scalameta/paradise/issues/209.
