### ISSUE TITLE
Parse failure for "a: Array[_] ⇒ format(t, (a map (_.asInstanceOf[AnyRef]): _*))"

### ISSUE THREAD

**Issue by raboof** [scalameta/scalameta#910]
When running sbt-scalahost 1.8.0 on akka, I get:
```
[error] failed to generate semanticdb for /home/aengelen/dev/akka/akka-actor/src/main/scala/akka/event/Logging.scala
:
[error] akka-actor/src/main/scala/akka/event/Logging.scala:1280: error: ) expected but identifier found
[error] case a: Array[_] ⇒ format(t, (a map (_.asInstanceOf[AnyRef]): _*))
[error]                                                                    ^
[error] 	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[error] 	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:18)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[error] 	at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:429)
[error] 	at scala.meta.internal.parsers.ScalametaParser.accept(ScalametaParser.scala:435)
[error] 	at scala.meta.internal.parsers.ScalametaParser.inParens(ScalametaParser.scala:333)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$makeTupleTermParens$1.apply(ScalametaParser.
scala:864)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$makeTupleTermParens$1.apply(ScalametaParser.
scala:864)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:413)
[error] 	at scala.meta.internal.parsers.ScalametaParser.makeTupleTermParens(ScalametaParser.scala:863)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$simpleExpr$1.apply(ScalametaParser.scala:204
5)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$simpleExpr$1.apply(ScalametaParser.scala:202
6)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:413)
[error] 	at scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:2026)
[error] 	at scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:2004)
[error] 	at scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:1980)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.sca
la:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.sca
la:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:413)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1672)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1600)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:407)
```

I plan to try to come up with a smaller reproducer based on latest scalameta master later, but wanted to record this in case I don't get to it any time soon.

**Comment by xeno-by** [comment]
Thanks! I'll look into this issue during the weekend.

**Comment by xeno-by** [comment]
Minimized:

```
import scala.meta._

object Test extends App {
  val input = "foo((bar: _*))"
  println(input.parse[Stat])
}
```

**Comment by xeno-by** [comment]
@olafurpg Wdyt about emitting semantic db generation failures as warnings or, even better, infos, so that they don't block our early adopters?

**Comment by xeno-by** [comment]
I've tried to fix this parser issue, but the fix is quite tricky, and it would benefit greatly from the ongoing 1.9 tree refactoring. So I suggest we somehow unblock the semantic db generation here, and in the meanwhile wait for the tree refactoring to come through.

Here's the sketch of my fix:
```diff
18:48 ~/Projects/Meta1x/sandbox (master)$ git diff
diff --git a/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala b/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
index 8cb5923b69..d19db82267 100644
--- a/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
+++ b/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
@@ -1594,24 +1594,10 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
    *               | `:' `_' `*'
    *  }}}
    */
-  def expr(): Term = expr(Local)
-
-  def unquoteExpr(): Term =
-    token match {
-      case Ident(_)    => termName()
-      case LeftBrace() => dropTrivialBlock(expr())
-      case KwThis()    => val qual = atPos(in.tokenPos, in.prevTokenPos)(Name.Anonymous()); next(); atPos(in.prevTokenPos, auto)(Term.This(qual))
-      case _           => syntaxError("error in interpolated string: identifier, `this' or block expected", at = token)
-    }
-
-  def unquoteXmlExpr(): Term = {
-    unquoteExpr()
-  }
-
   // TODO: when parsing `(2 + 3)`, do we want the ApplyInfix's position to include parentheses?
   // if yes, then nothing has to change here
   // if no, we need eschew autoPos here, because it forces those parentheses on the result of calling prefixExpr
-  def expr(location: Location): Term = autoPos(token match {
+  def expr(location: Location = Local, allowRepeated: Boolean = false): Term = autoPos(token match {
     case KwIf() =>
       next()
       val cond = condExpr()
@@ -1688,7 +1674,7 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
         t match {
           case ref: Term.Ref =>
             next()
-            t = atPos(ref, auto)(Term.Assign(ref, expr()))
+            t = atPos(ref, auto)(Term.Assign(ref, expr(allowRepeated = allowRepeated)))
           case app: Term.Apply =>
             def decompose(term: Term): (Term, List[List[Term.Arg]]) = term match {
               case Term.Apply(fun, args) =>
@@ -1711,7 +1697,13 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
           t = atPos(t, auto)(Term.Annotate(t, annots(skipNewLines = false)))
         } else {
           t = {
-            val tpt = typeOrInfixType(location)
+            val tpt = typeOrInfixType(location) match {
+              case dummy @ Type.Placeholder(Type.Bounds(None, None)) if isIdentOf("*") =>
+                if (allowRepeated) atPos(dummy, auto){ next(); Type.Name("_*") }
+                else syntaxError("repeated argument not allowed here", at = t)
+              case tpt =>
+                tpt
+            }
             // this does not correspond to syntax, but is necessary to
             // accept closures. We might restrict closures to be between {...} only.
             atPos(t, tpt)(Term.Ascribe(t, tpt))
@@ -1787,6 +1779,18 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
       t
   })

+  def unquoteExpr(): Term =
+    token match {
+      case Ident(_)    => termName()
+      case LeftBrace() => dropTrivialBlock(expr())
+      case KwThis()    => val qual = atPos(in.tokenPos, in.prevTokenPos)(Name.Anonymous()); next(); atPos(in.prevTokenPos, auto)(Term.This(qual))
+      case _           => syntaxError("error in interpolated string: identifier, `this' or block expected", at = token)
+    }
+
+  def unquoteXmlExpr(): Term = {
+    unquoteExpr()
+  }
+
   /** {{{
    *  Expr ::= implicit Id => Expr
    *  }}}
@@ -1935,7 +1939,7 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
    *                  | InfixExpr Id [nl] InfixExpr
    *  }}}
    */
-  def postfixExpr(): Term = {
+  def postfixExpr(allowRepeated: Boolean): Term = {
     val ctx  = termInfixContext
     val base = ctx.stack

@@ -2014,14 +2018,14 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
    *  PrefixExpr   ::= [`-' | `+' | `~' | `!' | `&'] SimpleExpr
    *  }}}
    */
-  def prefixExpr(): Term =
-    if (!isUnaryOp) simpleExpr()
+  def prefixExpr(allowRepeated: Boolean): Term =
+    if (!isUnaryOp) simpleExpr(allowRepeated)
     else {
       val op = termName()
       if (op.value == "-" && token.is[NumericLiteral])
         simpleExprRest(atPos(op, auto)(literal(isNegated = true)), canApply = true)
       else
-        atPos(op, auto)(Term.ApplyUnary(op, simpleExpr()))
+        atPos(op, auto)(Term.ApplyUnary(op, simpleExpr(allowRepeated)))
     }

   /** {{{
@@ -2037,7 +2041,7 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
    *                  |  SimpleExpr1 ArgumentExprs
    *  }}}
    */
-  def simpleExpr(): Term = autoPos {
+  def simpleExpr(allowRepeated: Boolean): Term = autoPos {
     var canApply = true
     val t: Term = {
       token match {
@@ -2056,7 +2060,23 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
           next()
           atPos(in.prevTokenPos, in.prevTokenPos)(Term.Placeholder())
         case LeftParen() =>
-          makeTupleTermParens(commaSeparated(expr()))
+          makeTupleTermParens {
+            val args = commaSeparated(argumentExpr())
+            args.map {
+              case arg: Term =>
+                arg
+              case arg: Term.Arg.Named =>
+              case arg: Term.Arg.Repeated =>
+                if (allowRepeated
+
+            }
+            val repeated = args.find(_.is[Term.Arg.Repeated])
+            repeated match {
+              case
+            }
+          }
+
+          syntaxError("repeated argument not allowed here", at = t)
         case LeftBrace() =>
           canApply = false
           blockExpr()
@@ -2129,14 +2149,12 @@ class ScalametaParser(input: Input, dialect: Dialect) { parser =>
   }

   def argumentExpr(): Term.Arg = {
-    expr() match {
+    expr(allowRepeated = true) match {
       case q: Quasi =>
         q.become[Term.Arg.Quasi]
-      case Term.Ascribe(t1, Type.Placeholder(Type.Bounds(None, None))) if isIdentOf("*") =>
-        next()
+      case Term.Ascribe(t1, Type.Name("_*")) =>
         atPos(t1, auto)(Term.Arg.Repeated(t1))
-      case Term.Assign(t1: Term.Name, Term.Ascribe(t2, Type.Placeholder(Type.Bounds(None, None)))) if isIdentOf("*") =>
-        next()
+      case Term.Assign(t1: Term.Name, Term.Ascribe(t2, Type.Name("_*"))) =>
         atPos(t1, auto)(Term.Arg.Named(t1, atPos(t2, auto)(Term.Arg.Repeated(t2))))
       case Term.Assign(t2: Term.Name, rhs) =>
         atPos(t2, auto)(Term.Arg.Named(t2, rhs))
```

**Comment by olafurpg** [comment]
> @olafurpg Wdyt about emitting semantic db generation failures as warnings or, even better, infos, so that they don't block our early adopters? upd. Maybe under a flag?

We can add support for `-P:scalahost:errorSeverity:info/warn/error` with info as the default. WDYT?

**Comment by xeno-by** [comment]
Sounds good!
