### ISSUE TITLE
NullPointerException in console/repl

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#926]
## Problem
I enabled semanticdb-scala in my project and ran `console` and got this error
```
(run-main-2) java.lang.NullPointerException

java.lang.NullPointerException
	at scala.meta.internal.scalahost.ScalahostPipeline.$anonfun$scalametaTargetroot$1(ScalahostPipeline.scala:22)
	at scala.Option.map(Option.scala:146)
	at scala.meta.internal.scalahost.ScalahostPipeline.scalametaTargetroot(ScalahostPipeline.scala:22)
	at scala.meta.internal.scalahost.ScalahostPipeline.scalametaTargetroot$(ScalahostPipeline.scala:19)
	at scala.meta.internal.scalahost.ScalahostPlugin.scalametaTargetroot$lzycompute(ScalahostPlugin.scala:11)
	at scala.meta.internal.scalahost.ScalahostPlugin.scalametaTargetroot(ScalahostPlugin.scala:11)
	at scala.meta.internal.scalahost.ScalahostPipeline$ScalahostComponent$ScalahostPhase.run(ScalahostPipeline.scala:54)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.interpreter.IMain._initialize(IMain.scala:129)
	at scala.tools.nsc.interpreter.IMain.initializeSynchronous(IMain.scala:149)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$11(ILoop.scala:992)
	at scala.tools.nsc.interpreter.ILoop.startup$1(ILoop.scala:964)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$1(ILoop.scala:1009)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:1023)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:82)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

## Expected

Scalahost to do nothing in the repl

**Comment by olafurpg** [comment]
Any idea @xeno-by how to detect when we are inside the repl? I would prefer to make it safe to use `-Xplugin:scalahost.jar` with the repl instead of forcing users to filter out the setting.

**Comment by xeno-by** [comment]
Here's one way of achieving this: https://github.com/xeno-by/scalameta/blob/master/scalahost/nsc/src/main/scala/scala/meta/internal/scalahost/HijackAnalyzer.scala#L18.

**Comment by xeno-by** [comment]
@olafurpg Is this still relevant now that sbt-scalahost is removed?

**Comment by olafurpg** [comment]
I'm still able to reproduce with `-Xplugin:/sdb.jar`, so it's still relevant. I suspect this will be a blocker for many.
