### ISSUE TITLE
Fragment:  Illegal character in path 

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#975]
```scala
[info]   java.net.URISyntaxException: Illegal character in path at index 83: file:/Users/ollie/dev/sbthost/sbthost/tests/target/streams/test/test/isModule=false name=scala.meta.tests.SbtFileTest/test/out
[info]   at java.net.URI$Parser.fail(URI.java:2848)
[info]   at java.net.URI$Parser.checkChars(URI.java:3021)
[info]   at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[info]   at java.net.URI$Parser.parse(URI.java:3053)
[info]   at java.net.URI.<init>(URI.java:588)
```

**Comment by olafurpg** [comment]
I am unable to reproduce. I tried

```scala
  test("Filename with spaces #975") {
    val fragment = Fragment(PathIO.workingDirectory, RelativePath("isModule=true name=foo/bar"))
    val obtained = fragment.uri
    println(obtained)
      // file:///Users/ollie/dev/scalameta/isModule=true%20name=foo/bar
  }
```

Reopen if this surfaces again.
